function rolar() {
  var tabela = document.getElementById('selecionar-tabela').value
  var min = 1
  var max = 100
  var resultado = Math.floor(Math.random() * (max - min + 1)) + min

  switch (tabela) {
    case 'ancient':
      var valoresTabela = [
        '1: Pães Mofados: Comida, cura 5 pontos de vida, mas tem um sabor simplesmente horrível',
        '2: Levitação: Feitiço de INT, encanta um alvo para flutuar até 1,8 metros de altura por 1D4 rodadas',
        '3: Identificar: Feitiço de INT, dá a um alvo +3 em uma rolagem de INT/Pesquisa, não é necessária uma tentativa para lançar o feitiço',
        '4: 10 Flechas Mágicas: Item, Dano mágico com um tiro de arco, pode ser recuperada, destruída em falha crítica',
        '5: Lanche Veloz: Comida, ganha um bônus de MOVIMENTO após seu próximo MOVIMENTO',
        '6: Picadas de Aranha: Comida, cura 2D6 pontos de vida, mas você está basicamente comendo um inseto',
        '7: Banquete de Dedos: Comida, cura todos os aliados em 1D8 se estiverem a CURTA distância',
        '8: Armadura de Fé: Feitiço de WIS, dá a um alvo +3 DEFESA por 1 turno',
        '9: Espada de Prata: Arma, +1 Esforço, propriedades de prata',
        '10: Rede com Espinhos: Arma, teste de FOR para escapar, emaranhado, mover apenas para PERTO e todas as rolagens difíceis',
        '11: Kit de Disfarce: Item, sempre que enganar um estranho, faça um esforço FINAL e rolagens FÁCEIS',
        '12: Colete de Mithril: Armadura, subtrai 2 de todo o dano de arma contra você',
        '13: Amuleto de Égide: Item, role 1D8 quando morrer',
        '14: Coração de Iradrum: Comida, por 24 horas após comer, se você chegar a 0 pontos de vida, recupera instantaneamente 1 ponto de vida',
        '15: Bacon Irado: Comida, cura 3D12 pontos de vida',
        '16: Botas de Nado: Armadura, +1 DEFESA, esforço duplo e alcance ao nadar',
        '17: Gar Vermelho: Comida, cura para pontos de vida completos, absorve o próximo ataque ileso',
        '18: Manto das Sombras: Armadura, +1 DEFESA, rolagens FÁCEIS ao se esconder',
        '19: Escudo do Leão: Armadura, +2 DEFESA, aliados que estão PERTO também recebem +2 DEFESA',
        '20: Elmo do Demônio: Armadura, +1 DEFESA, +3 CHA ao intimidar',
        '21: Toque de Cura: Feitiço de WIS, toque para curar um aliado com Esforço Mágico',
        '22: Nova de Cura: Feitiço de WIS, cura todos os aliados PERTO com Esforço Mágico duplo',
        '23: Videira de Agarrão: Feitiço de WIS, puxa um monstro ou aliado PERTO com você, resistência oposta de FOR para resistir',
        '24: Raio de Luz: Magia INT, queima 1-12 HP e adiciona a um ataque mágico, dobra contra armaduras de metal.',
        '25: Explosão de Gelo: Magia INT, causa dano mágico e imobiliza o alvo por 1 turno.',
        '26: Bomba Arcana: Magia INT, um orbe brilhante que explode em 2D12 após 1D4 ROUNDS, alcance PERTO.',
        '27: Machado de Batalha Rasgado: Arma, -2 para tentativas, mas role ESFORÇO FINAL a cada vez.',
        '28: Bola de Fogo: Magia INT, atinge quaisquer alvos dentro do alcance PERTO de uma determinada localização.',
        '29: Botas de Garra: Armadura, permite andar em qualquer superfície em qualquer direção sem precisar de um teste.',
        '30: Pedra do Coração: Item, aumenta em 1 o número máximo de Corações.',
        '31: Encantamento: Magia SAB, encanta um item para realizar um esforço mágico e adicionar +1 a cada Coração de Esforço gasto.',
        '32: Grimório Encantado: Item, um resultado natural 19+ é considerado um acerto crítico ao conjurar magias.',
        '33: Amuleto do Guerreiro: Item, permite usar esforço mágico com qualquer arma.',
        '34: Escudo Divino: Magia SAB, encanta um alvo para absorver o próximo esforço feito contra ele.',
        '35: Cajado dos Elementos: Item, triplica o esforço mágico elemental feito com magias INT.',
        '36: Capa de Aras: Armadura, desvia 1 ataque de arma contra você por turno.',
        '37: Luvas de Prata: Armadura, +3 FOR ao agarrar ou agarrar, propriedades de prata.',
        '38: Gancho de Ferro: Arma, use um turno para puxar um alvo até a sua localização, alcance LONGE.',
        '39: Repelir Mortos-vivos: Magia SAB, por 1 turno, repele 1D8 mortos-vivos, que não podem se aproximar dentro do alcance PERTO.',
        '40: Fragmento de Terror: Item, causa pânico, alvos vivos devem resistir com SAB ou fugir por um turno.',
        '41: Ressurreição: Magia SAB, rolagem DIFÍCIL, em 4 ROUNDS um alvo falecido tocado é revivido com 1 HP.',
        '42: Orbe do Dragão: Item, causa 4D12 de dano mágico de fogo, alcance LONGE, o item é destruído.',
        '43: Elmo do Dragão: Armadura, +2 DEFESA, o usuário é imune a danos infligidos por fogo.',
        '44: Anel de Fantasmas: Item, role INT para criar um clone PERTO que realiza o mesmo ataque ou ação.',
        '45: Coroa da Loucura: Item, faz um alvo realizar uma ação aleatória (rolagem do GM).',
        '46: Asas de Roc Defumadas: Comida, permite voar por 4 ROUNDS.',
        '47: Gar Preto: Comida, +10 DEFESA por 4 ROUNDS.',
        '48: Beijo da Rainha: Comida, Sua próxima ação é um sucesso crítico automático.',
        '49: Afiamento: Magia de INT, Adicione +2 de esforço a uma arma, uma vez por arma.',
        '50: Escudo Espinhoso: Armadura, os ataques falhos do inimigo são respondidos com Dano de Arma (sem bônus).',
        '51: Arco das Águias: Arma, use um turno extra mirando para causar o dobro de dano',
        '52: Enxame: Magia de SAB, lançada em uma área vista, causa dano mágico nos alvos PRÓXIMOS por 1D4 ROUNDS.',
        '53: Curandeiro: Magia de INT, conserta instantaneamente um item ou arma danificados.',
        '54: Escudo de Crânio: Armadura, +2 DEFESA, também pode ser usada como arma mágica.',
        '55: Lança de Prata: Arma, mágica, +3 de TENTATIVA de DEX quando arremessada, propriedades de prata.',
        '56: Bigorna Anã: Item, uma vez a cada 1D12 dias, cria uma arma com +3 de TENTATIVA ou bônus de ESFORÇO.',
        '57: Livro de Habilidades: Item, com 3 sucessos, ganhe permanentemente +1 para um tipo específico de TENTATIVA.',
        '58: Anel de Fogo: Item, dobra todo o dano de fogo infligido.',
        '59: Espada Flamejante: Arma, mágica, adiciona 1D4 de dano de queimadura por 1D4 ROUNDS nos alvos acertados.',
        '60: Anel de Gênio: Item, use ESFORÇO FINAL com qualquer rolagem bem-sucedida de INT.',
        '61: Cálice de Udin: Item, dobra os efeitos de qualquer comida consumida.',
        '62: Anel de Aras: Item, ao se recuperar, preencha um CORAÇÃO além de sua RECUPERAÇÃO normal.',
        '63: Pedra do Coração: Item, adiciona 1 coração ao seu máximo.',
        '64: Translocar: Magia de INT, troca de lugar com um aliado que você pode ver.',
        '65: Máscara de Mofune: Armadura, +1 DEFESA, role ESFORÇO FINAL ao intimidar.',
        '66: Anel de Poder: Item, dobra todo o ESFORÇO MÁGICO.',
        '67: Selo do Rei: Item, ter a última palavra em decisões de grupo e ser amado por isso.',
        '68: Martelo Anão: Arma, arma mágica, role ESFORÇO FINAL dobrado em 20 natural.',
        '69: Ferramentas de Ladrão: Item, +3 de TENTATIVA E ESFORÇO DOBRADO ao abrir baús.',
        '70: Anel de Gigantes: Item, +1 de STR, +1 DEFESA.',
        '71: Botas Magistrais: Item, +1 DEX',
        '72: Caneca do Rei: Item, +1 CON',
        '73: Amuleto dos Segredos: Item, +1 INT',
        '74: Contas de Meditação: Item, +1 WIS',
        '75: Casacos Magistrais: Item, +1 CHA',
        '76: Kit de Armadura: Item, +2 DEFESA',
        '77: Pedra de Fogo: Item, +1 Esforço MÁGICO',
        '78: Kit de Armas: Item, +2 Esforço de Armas',
        '79: Luneta de Diamante: Item, +6 WIS em tentativas de Exploração',
        '80: Anel Berserk: Item, +3 em Esforço ÚLTIMO',
        '81: Baluarte Sagrado: Feitiço WIS, Toque um aliado, eles são imunes a Esforço não-MÁGICO por 4 ROUNDS',
        '82: Tempestade: Feitiço WIS, Tudo com alcance LONGO é atingido por granizo para MÁGICA',
        '83: Carne Seca: Comida, Regenera 1D12 HP para os próximos 4 ROUNDS',
        '84: Hauberk de Adamantina: Armadura, +4 DEFESA',
        '85: Bebedor de Vida: Arma, Arma Mágica, Cura metade do dano causado a alvos vivos',
        '86: Pulseiras de Poder: Armadura, DEFESA +1, Role 1D8 para qualquer Esforço Básico',
        '87: Cinto de Ferro Gut: Armadura, +1 DEFESA, Se falhar em um teste de CON, tente mais uma vez',
        '88: Cerveja da Morte: Comida, Retorna da morte com 10 HP. Desperdiçada se não for usada dentro de 1 dia após beber',
        '89: Cerveja da Vida: Comida, Beba em batalha. Qualquer aliado que o tocar cura 1D12 HP uma vez',
        '90: Óculos do Gadgets: Armadura, +1 DEFESA, Criar ou consertar máquinas é sempre FÁCIL',
        '91: Pena de Queda: Item, Você não pode se machucar por danos de queda de qualquer altura',
        '92: Dobra-Tempo: Item, Se o GM rolar um cronômetro, role novamente. A segunda rolagem será final',
        '93: Maça do Trovão: Arma, Mágica, Qualquer alvo atingido fica atordoado em seu próximo TURNO',
        '94: Corcel Relâmpago: Item, Invoca um corcel voador. O que levaria um dia, leva 1 ROUND',
        '95: Anel da Sorte Estranha: Item, Se você rolar um 1 duas vezes, seu erro causa algo benéfico',
        '96: Anel Artesão de Magias: Item, Se você rolar um crítico ao lançar uma magia, tente outra magia imediatamente',
        '97: Botas da Pressa: Armadura, DEFESA +1, Após uma ação, você também pode se mover novamente',
        '98: Anel de Matadores: Item, Se você fizer um ataque bem-sucedido com uma arma, ataque novamente para o ULTIMATE',
        '99: Coroa Astral: Armadura, +2 DEFESA, Ao lançar uma magia crítica, lance através de um aliado',
        '100: Banquete dos Reis: Comida, Todos os aliados restauram HP completo e recebem um Baú',
      ]
      break
    case 'shabby':
      var valoresTabela = [
        '1: Ração do Soldado: Comida, cura 1D4 HP',
        '2: Ração do Capitão: Comida, cura 1D6 HP',
        '3: Bolsa de Moedas: 1D10 moedas',
        '4: Bolsa de Moedas Grande: 2D10 moedas',
        '5: Espada Comum: Arma, lâmina de aço padrão com uso pesado',
        '6: Escudo Usado: Armadura, +2 DEFESA, muito desgastado, quebrará no 3º ataque',
        '7: Ferramentas do Mecânico: Item, martelo, chave inglesa, role testes FÁCEIS em tarefas mecânicas',
        '8: Capacete Comum: Armadura, +1 DEFESA',
        '9: Roupas de Trabalhador: Armadura, +1 DEFESA, macacão, luvas e chapéu duráveis',
        '10: Caixa de Moedas: 3D12 moedas',
        '11: Lanterna: Item, lanterna de caixa fácil de acender, ilumina tudo dentro do alcance PRÓXIMO',
        '12: Espigões de Escalada: Item, escalar uma rota normalmente. Qualquer um que siga role FÁCIL',
        '13: Corda de 50 pés: Item, 50 pés de corda de fibra resistente enrolada',
        '14: Barra de Alavanca: Item, uma barra de ferro de 3 pés com uma ponta curvada, role FÁCIL ao forçar portas',
        '15: Kit de Primeiros Socorros: Item, bandagens para curativo de campo, consuma para dar 1 HP a um aliado moribundo',
        '16: Escada: Item, uma escada de madeira com 12 degraus, com 12 pés de altura',
        '17: Capa de Lã: Armadura, +1 DEFESA, uma capa com capuz típica para uso no inverno',
        '18: Pele de Gar Envelhecido: Comida, consuma para tornar seu próximo teste FÁCIL',
        '19: Armadilha de Caça: Item, armadilha reutilizável de mola, imobilizará e causará 1 dano',
        '20: Gema Empoeirada: Valor de 1D100 moedas',
        '21: Tocha: Item, Um pedaço de pau embebido em óleo envolto em tecido, ilumina o raio PRÓXIMO por D8 RODADAS',
        '22: Kit de Rebites: Item, Um pequeno martelo e punção para pregar rebites em couro ou madeira',
        '23: Cartucho de Fumaça: Item, Cria uma nuvem de fumaça com raio PRÓXIMO por 1D4 RODADAS',
        '24: Perna de Peru: Comida, Cura 1D10 HP',
        '25: Elixir Estimulante: Comida, no seu próximo turno, mova para LONGE como se estivesse no raio PRÓXIMO',
        '26: Livro em Branco: Item, Um livro em branco em estilo de diário com uma caneta embainhada',
        '27: Cortadores de Metal: Item, Um alicate para cortar barras, role Esforço MÁXIMO ao fazer isso',
        '28: Pequena Tenda: Item, Abriga 3 pessoas, embala em um pacote pequeno',
        '29: Lona de Tarp: Item, Um quadrado de pano durável com raio PRÓXIMO em cada lado',
        '30: Paraquedas Usado: Item, Deploy quando caindo para anular o dano, 1% de chance de falha',
        '31: Reserva de Moedas: 2D100 Moedas',
        '32: Arco Longo Usado: Arma, Tem 10% de chance de quebrar quando usado',
        '33: Munição Comum: Munição padrão, 10 unidades, role para o tipo',
        '34: Adaga Comum: Arma, Lançável, Perfurante, Rápida',
        '35: Lança do Piqueiro: Arma, Tem alcance PRÓXIMO, não pode ser lançada',
        '36: Barra de Ferry: Item, Uma vara resistente que pode chegar LONGE, muito difícil de carregar',
        '37: Equipamento de Pesca: Item, Equipamento de pesca padrão de baixo custo e vara',
        '38: Conjunto de Cozinha: Item, Panela, pratos, temperos. Cura 5 HP ACIMA do limite máximo quando acampando',
        '39: Ímã Grande: Item, Ímã poderoso que pode suportar 100 libras',
        '40: Serrote: Item, usado para cortar metal ou madeira com precisão e lentamente',
        '41: Refeição do Viajante: Comida, Cura até 5 pessoas por 1 CORAÇÃO',
        '42: Casaco Forrado de Pele: Armadura, +1 DEFESA, Ignora efeitos negativos do frio extremo',
        '43: Luvas à Prova de Corrosão: Armadura, +1 DEFESA, Couro imune a ácido ou corrosão',
        '44: Estandarte de Guerra: Item, Um estandarte de lona montado em um poste de 10 pés, sem marcações',
        '45: Âncora: Item, Uma âncora de ferro e corrente de 50 pés usada em barcos de tamanho médio',
        '46: Roupas Nobres: Armadura, +1 DEFESA, Um conjunto de roupas formais de alta qualidade e sob medida',
        '47: Jarro de Óleo Velho: Item, Sobras de trabalho mecânico, altamente inflamável, escorregadio',
        '48: Megafone: Item, Um chifre cônico com empunhadura de pistola, transmite um grito para o DOBRO da distância LONGE',
        '49: Guincho de Catraca: Item, Uma corrente bissectada por uma alavanca, puxa objetos MUITO PESADOS',
        '50: Kit de Espigões de Armadura: Item, Adicione espigões a qualquer armadura, atacantes perdem 1 HP ao atingir',
        '51: Flechas de Mestre: Item, Duplica o Esforço de Armas em um acerto, 3 unidades',
        '52: Jarra de Moscas: Item, Uma jarra de vidro grande cheia de moscas, resquício de trabalho científico',
        '53: Lado de Carne Assada: Comida, Cura 3 pessoas em 1D12',
        '54: Crânio Deformado: Item, Um artefato estranho mantido por algum esquisitão',
        '55: Carro de Mão: Item, Uma plataforma de metal com quatro pequenas rodas, usada para transportar cargas',
        '56: Caneca Entalhada: Item, Uma caneca de bebida exclusivamente feita, enorme',
        '57: Gema Luminosa: Vale 3D100 Moedas',
        '58: Botas do Ferreiro: Armadura, +1 DEFESA, Imune ao fogo ou superfícies quentes',
        "59: Sinalizador: Item, Um sinalizador de magnésio que queima brilhantemente em amarelo, mesmo debaixo d'água",
        '60: Chifre de Sinal: Item, Quando tocado, pode ser ouvido a 1 milha de distância',
        '61: Cidra Gar Dura: Comida, Ignora o próximo dano de 10 causado a você',
        '62: Luneta de Vidro: Item, Anexa-se a uma arma à distância, +1 DEX ao usar essa arma',
        '63: Polia de Carga Enorme: Item, Usada com corda para levantar facilmente objetos enormes',
        '64: Pedra Ímã: Item, Um cubo incrivelmente pesado de ferro sólido com uma alça em cima',
        '65: Vareta de Aço: Item, Resto de alguma máquina, com 3 pés de comprimento, quase inquebrável',
        "66: Equipamento de Mergulho: Item, Máscara, nadadeiras e bexiga de ar, 4 RODADAS debaixo d'água, reutilizável",
        '67: Ferramentas de Mineração: Item, Faça rolagens FÁCEIS ao escavar',
        '68: Corrente de Ouro: Item, Uma vez usada pelos ricos, vale 1D100 x 5 moedas',
        '69: Barril de Gar Dourado: Comida, 2 HP para até 50 pessoas, uma vez aberto, azeda em 1 dia',
        '70: Roupa de Pássaro: Armadura, +1 DEFESA, Uma fantasia de penas teatrais e máscara para ocasiões festivas',
        '71: Pá: Item, Uma pá de aço resistente e madeira',
        '72: Cadeado e Chave: Item, Cadeado de aço reforçado',
        '73: Capa Gilly: Armadura, +1 DEFESA, Uma capa folhosa, faça rolagens FÁCEIS de furtividade em ambientes naturais',
        '74: Besta Rápida: Arma, Tem 10% de chance de disparar um segundo DARDOM quando disparada',
        '75: Frasco de Ácido: Item, Algumas onças de ácido clorídrico concentrado',
        '76: Arnês de Bolsa do Escoteiro: Armadura, +1 DEFESA, Amplia a capacidade de transporte para 12 LOOTS',
        '77: Isca de Caçador: Item, Uma gosma não perecível que atrai a vida selvagem por até 1 milha',
        '78: Fole do Ferreiro: Item, Um fole enorme para avivar o fogo a temperaturas incríveis',
        '79: Bolsa de Rolamentos de Esfera: Item, Um pequeno saco de esferas de aço inoxidável de vários tamanhos',
        '80: Sino de Cabra: Item, Uma coleira de couro com sino de ferro, tamanho ajustável',
        '81: Maca de Socorro: Item, Carregue um aliado caído sem fazer testes de FOR',
        '82: Jaqueta de Armeiro: Armadura, +1 DEFESA, Aumenta a quantidade máxima de armaduras vestíveis para 11',
        '83: Um Bife de Qualidade: Comida, Cura o HP completo',
        '84: Colete Flutuador: Item, Usado para evitar fadiga ao nadar ou afogamento em água agitada',
        '85: Baralho de Cartas: Item, Jogue inúmeros jogos ou faça truques de salão',
        '86: Kit de Açougueiro: Item, Um pano enrolado com numerosas facas, anzóis e cutelos',
        '87: Pulverizador de Insetos do Agricultor: Item, Uma bomba manual cheia de mistura de vinagre',
        '88: Equipamento de Montaria: Item, Arreios de couro, sela para qualquer número de montarias de animais',
        '89: Kit de Reparo de Armadura: Item, Suprimentos e ferramentas reutilizáveis para consertar qualquer armadura',
        '90: Equipamento de Navegação: Item, Lunetas e mapas para navegar, faça rolagens FÁCEIS de navegação.',
        '91: Amuleto Sagrado de Prata: Item, Propriedades de prata, um símbolo inspirador do bem.',
        '92: Gema Cósmica: Valor de 1000 moedas.',
        '93: Elixir Elemental: Comida, ao encantar, consuma para adicionar uma propriedade elemental.',
        '94: Manual de Artes Marciais: Item, ao lutar com as mãos nuas, cause Dano de Arma.',
        '95: Mapa Local: Item, obtenha todas as localizações pertinentes num raio de 25 milhas.',
        '96: Frasco de Resolução: Comida, beba para adicionar UM ESFORÇO FINAL à sua próxima Tentativa bem-sucedida.',
        '97: Kit de Alquimia: Item, gaste 1 CORAÇÃO de esforço para produzir uma Poção aleatória de uso único.',
        '98: Sinete do Império: Armadura, +1 DEFESA, o sinal de um membro graduado da ordem cósmica.',
        '99: Pedra Runica: Item, se você for morto em batalha, retorne de Asgard... mas como?',
        '100: Luz dos Deuses: Item, destrua esta gema para levantar um aliado MORRENDO para HP completo.',
      ]
      break
    case 'cursed':
      var valoresTabela = [
        '1: Sanduíche de Alga: Comida, Cura 3 PV, Cheiro de água salgada e porão por 1 semana.',
        '2: Maldição de Arn: Magia de INT, Apodrece um alvo com 1 de Dano/rodada/1 dia, sofrendo também com a podridão.',
        '3: Armadilha Mental: Magia de INT, Uma vez aprendida, perde 1 de INT, toque em um alvo para lançar o mesmo efeito.',
        '4: 10 Flechas Terríveis: Item, Flechas Mágicas, NUNCA atingem o alvo, voltando como um bumerangue em 1.',
        '5: Pão de Passo Podre: Comida, Cura 3 PV, Só pode se mover PERTO por 1D4 de suas RODADAS.',
        '6: Filhotes Crus: Comida, Ganha 3 PV, teste de CON ou vomita, odeia ovos por 1 mês.',
        '7: Vermezinhos: Comida, Cura 2D6 PV, Todos os testes de CON são AGORA DIFÍCEIS por 24 horas.',
        '8: Espada Partida: Arma, +2 Tentativas/Esforço, não pode ser largada, lentamente se transforma em uma cabra.',
        '9: Escudo de Tartaruga: Armadura, +3 DEFESA, teste de CON DIFÍCIL para largar, ocupa 3 espaços.',
        '10: Coroa das Memórias: Item, teste de INT DIFÍCIL para remover, devora as melhores memórias do usuário.',
        '11: Elmo Esmagador de Crânios: Armadilha, Fecha com força causando Dano de Arma, causando dano novamente para remover.',
        '12: Aperto de Mão do Inferno: Armadilha, Escultura de mão, quando tocada, agarra com um aperto de STR +5.',
        '13: Anel das Lágrimas: Item, -1 de SAB, Para remover o anel, um receptor disposto deve ser encontrado.',
        '14: Machado Destruidor: Arma, +1 de STR, Uma vez lutando, você é compelido a terminar a matança.',
        '15: Pasta de Fígado de Agnar: Cura 2D12, Aliados PRÓXIMOS fazem teste de CON ou sofrem 1 de dano de afundamento.',
        '16: Olho da Bruxa: Item, Olhe através para localizar o mal, por 1 semana, veja o mal se escondendo em todos os lugares.',
        '17: Urna de Gafanhotos: Armadilha, Se aberta, libera um enxame de Gafanhotos de 2 CORAÇÕES.',
        '18: Capa de Peso Esmagador: Armadura, +1 DEFESA, teste de STR DIFÍCIL para remover, todos os testes são DIFÍCEIS.',
        '19: Escudo de Dentes: Armadura, +3 DEFESA, Se você fizer uma matança, o escudo comerá os restos.',
        '20: Luva de Agulhas: Armadilha, Uma luva de metal com agulhas envenenadas, 5 PV de dano.',
        '21: Bomba Mágica: Armadilha, Se saqueada, nuvem de gás com ALCANCE LONGO, gás anula magia por 1D4 RODADAS',
        '22: Botas de Peixe: Armadura, +1 DEFESA, Nade até DUPLA ALCANCE LONGO, cresça lentamente guelras',
        '23: Elmo de Sapos: Armadura, -3 CAR, remoção DIF STR, coaxa ao falar, fale com sapos',
        '24: Arco do Ódio: Arma, Mágica, DIF WIS para largar, erra o alvo e atinge um alvo aleatório',
        '25: Lâmina Congelante: Arma, Mágica, DIF WIS e 2D6 de dano frio para largar',
        '26: Parasita K’Tuul: Armadilha, Gruda no rosto, controla você completamente, remoção DIF CON',
        "27: Gerador de Ovos K'Tuul: Armadilha, Lança nuvem de esporos, em 1D8 RODADAS, eclodem em você",
        "28: Espinho K'Tuul: Armadilha, Um espinho preto atravessa sua mão causando 1D6 de dano",
        "29: Respirador K'Tuul: Armadura, -2 CAR, Respire em qualquer lugar, se usado por 3 RODADAS, permanente",
        '30: Luva de Tentáculo: Item, +2 FOR, -3 CAR, Um chicote bizarro com farpas substitui um braço',
        '31: Gelo Adesivo: Armadilha, Saqueador fica preso em um baú congelado, imobilizado até que o baú seja destruído',
        '32: Caneca do Bêbado: Item, DIF CON e -1 CON para largar, sede constante por Gar',
        '33: Amuleto da Certeza: Item, DIF CAR para remover, +1 CAR, Caminhe para o perigo como se fosse invencível',
        '34: Pé de Corvo: Item, Natural 20 para largar, Deseje o Pé de Corvo acima de tudo, até mesmo aliados',
        '35: Cajado de Serpentes: Item, +3 CAR, o usuário é atraído para usos sádicos da magia',
        '36: Manto de Vapor: Armadura, +2 DEFESA, Verificações de Furtividade FÁCEIS, se usado por 1D8 dias, torna-se vapor',
        '37: Machado de Guerra de Crânios: Arma, Mágica, DIF CAR para largar, força você a colecionar crânios',
        '38: Máscara do Horror: Armadilha, Um rosto humano horrendamente deformado, -5 CAR, 2D12 de dano para remover',
        '39: Hambúrguer de Fungo: Comida, Cura 1 PV, Perda de -2 PV por rodada, Verificações de CON DIF até ser curado completamente',
        '40: Visão do Medo: Armadilha, Uma presença ilusória de medo, o Saqueador deve fugir LONGE em uma direção aleatória.',
        '41: Uma Caixa Adorável: Armadilha, DIF CAR para largar, Nunca a abra, NINGUÉM pode abri-la! É minha!',
        '42: Galho Feio: Arma, Cajado Mágico, Causa dano de -1 CAR na primeira vez que acertar um alvo',
        '43: Pão Faminto: Comida, Cura 1D6 PV, Fique faminto insaciavelmente por 1D6 dias',
        '44: Dados do Mentiroso: Item, Para os próximos 3 lançamentos, minta para o seu grupo sobre o que você tirou, e depois destrua o item',
        '45: Anel da Traição: Item, DIF CON para remover, Escolha um aliado, e fique convencido de que eles te odeiam',
        '46: Colar do Declínio: Item, DIF CON para remover, Envelhece 10 anos a cada rodada',
        '47: Anel da Chama: Item, Adiciona 1D6 de dano de fogo aos ataques, Itens inflamáveis em sua posse queimam',
        '48: Coroa do Antinatural: Item, Duplo ESFORÇO contra qualquer coisa de madeira, Seus itens de madeira se desintegram',
        '49: Broche de Mira: Armadilha, DIF CON para remover, Pedra suga 2 PV por ataque bem-sucedido',
        '50: Cinto de Fardos: Armadilha, DIF FOR para remover, Um peso esmagador, Ocupa 5 espaços de equipamentos',
        '51: Cogumelo Glowcap: Comida, Cura 1 CORAÇÃO, Experimente alucinações por 1D4 dias',
        '52: Armadura Felina: Armadura, +6 DEFESA, Nenhuma outra armadura pode ser equipada, adquira hábitos / aparência malignos',
        '53: Machado Felino: Arma, Mágica, DIF FOR para largar, Quando mata, ataque um alvo ALEATÓRIO PRÓXIMO',
        '54: Elmo dos Mortos: Armadura, +2 DEFESA, Adquira propriedades de morto-vivo, remova somente quando MORRENDO',
        '55: Demônio das Flores: Armadilha, Libera um demônio, tudo o que ele toca fica sufocado com vinhas / flores',
        '56: Agasalho Gnômico: Comida, Caia para 1 PV, Se curado, torne-se um Gnomo Cinzento, -3 CAR, -2 FOR por 1D4 dias',
        '57: Livro das Mentiras: Item, DIF INT para se libertar, Convencido de falsidades, todas as jogadas de INT são DIFÍCEIS',
        '58: Besta Magnética: Arma, +2 Tentativas / Esforço, DIF FOR para separar da armadura de metal',
        '59: Bússola do Mentiroso: Armadilha, DIF INT para largar, Convencido de que a pior maneira é a melhor maneira',
        '60: Risadas: Armadilha, Um boneco de macaco fofo, CAR 18 para largar, Ri constantemente de coisas terríveis',
        '61: Agasalho de Pântano: Comida, Perca 3 PV, Cerveja de lama pegajosa o torna INCAPAZ DE COMER por 1D6 dias',
        '62: Bolsa de Aranha: Item, Uma bolsa que não larga, FOR 15 para remover, -5 CAR, Reduza a capacidade de carga para 5',
        '63: Pedra do Coração Negro: Armadilha, Você só tem 1 CORAÇÃO por 1D4 dias, não importa seu máximo real',
        '64: Conjuração de Aazul: Magia INT, Invoca 1D4 demônios imp que desejam carne viva',
        '65: Anel do Desejo de Morte: Item, DIF INT para remover, Uma vontade súbita e poderosa de morrer com glória',
        '66: Efígie de Azatoth: Armadilha, Uma estátua demoníaca, Toque: por 1D4 dias, a perda de sangue gera um tentáculo',
        '67: Orbe do Caçador: Armadilha, Um orbe implacável voa e caça você e seus aliados, 3 CORAÇÕES, Mágica',
        '68: Lança do Empalador: Arma, Mágica, DIF CAR para largar, Sinta-se compelido a empalar suas vítimas',
        '69: Amuleto Sussurrante: Item, DIF CAR para remover, Não para de falar, Todas as jogadas de Furtividade são DIFÍCEIS',
        '70: Bolsa de 100 Moedas Falsas: Comerciantes e outros te odeiam por enganá-los',
        '71: Capacete de Agnar: Armadura, DEFESA +2, FOR DIF para remover, Ganhe metade de qualquer benefício de COMIDA.',
        '72: Caneca do Morto: Item, CHA DIF para largar, Inverte qualquer benefício da bebida em dano.',
        '73: Livro do Esquecimento: Armadilha, Desintegra-se ao ser lido, Perca um ITEM EQUIPADO por 1D4 dias.',
        '74: Garrafa de Swill: Comida, 6 goles, Receba 2 de dano com cada gole, mas fique irremediavelmente viciado por 1D4 dias.',
        '75: Foice do Devastador: Arma, Mágica, CHA DIF para largar, Você agora está proibido de curar seus aliados.',
        '76: Kit de Armadura do Tolo: Armadilha, Quando usado, deduza 1 do seu total de DEFESA.',
        '77: Kit de Arma do Tolo: Armadilha, A arma que você modificar vai QUEBRAR em seu próximo ataque falho.',
        '78: Chicotes de Espinhos Explosivos: Armadilha, SAQUEADO, você e todos os aliados PRÓXIMOS ficam imobilizados por 1D4 RODADAS.',
        '79: Fumo de Cachimbo Apodrecido: Item, INT DIF para largar, Viciante, Anula o bônus de INT por 1D4 horas.',
        '80: Gás Atordoante: Armadilha, O saqueador respira uma nuvem de névoa roxa, todos os testes de DEX são DIFÍCEIS por 1D4 dias.',
        '81: Ácaros nos Olhos: Armadilha, Uma colônia de pequenos ácaros explode em seus olhos, você fica CEGO por 1D4 horas.',
        '82: Adaga do Rancor: Arma, CHA DIF para largar, Qualquer vez que você for persuadido, esfaqueie aquela pessoa!',
        '83: Pulseira de Crânio: Item, INT DIF para largar, Quando usada, role novamente MORRENDO se acima de 3.',
        '84: Lâmina da Ganância: Arma, Mágica, CHA DIF para largar, Vá atrás de TODOS OS BAÚS.',
        '85: Manto do Desespero: Armadura, DEFESA +1, CHA DIF para remover, Critique constantemente os planos dos seus aliados.',
        '86: Beleza Pura: Armadilha, CHA DIF para desviar o olhar depois de aberta, Se outros olharem, o mesmo é necessário para escapar.',
        '87: Raio da Morte: Armadilha, Faça um teste de CON ou seja instantaneamente reduzido a 0 HP por um raio negro de magia.',
        '88: Gorro da Loucura: Item, INT DIF pra remover, Todos os testes de INT são DIFÍCEIS, Fique completamente louco.',
        '89: Vinho de Sangue: Comida, Perca 4 HP, Você não pode curar nenhum HP até beber sangue humano uma vez.',
        '90: Casaco de Pele Selvagem: Armadura, DEFESA +3, CHA DIF para remover, Seja animal em ação e pensamento.',
        '91: Pedra Ângular: Item, DIFÍCIL INT para remover, Quando vestido, receba o dobro de dano de qualquer queda.',
        '92: Escorrega Tempo: Armadilha, Qualquer que seja o tempo do cronômetro do DM quando SAQUEADO, acelere-o em 1.',
        '93: Flecha Armadilhada: 1 munição, Quando disparada, causa Dano Mágico em qualquer coisa dentro do alcance LONGO.',
        '94: Lâmina de Azatoth: Arma, Mágica, Uma espada tentacular, Convencido de que O Devorador deve surgir.',
        '95: Couraça do Levante: Armadura, DEFESA +3, para remover, Todas as coisas mortas PRÓXIMAS a você se levantam como mortos-vivos.',
        '96: Capacete Berserker: Armadura, DEFESA +2, Bônus de ESFORÇO DUPLICADO PARA ARMAS, escolha alvos aleatoriamente.',
        '97: Ramo de Oliveira: Item, DIFÍCIL CHA para largar, Recuse-se a ferir qualquer ser vivo.',
        '98: Bomba Fedorenta: Armadilha, Você e seus aliados cheiram terrivelmente, -5 CHA e cheiro por 1 milha por 1D4 dias.',
        '99: Cruz de Ferro Frio: Item, DIFÍCIL WIS para remover, Você não pode usar magias de WIS.',
        '100: Chave do Ogdru: Item, Se usada, um buraco de fechadura aparece, alarga-se, convoca 1D8 Tentáculos Gigantes.',
      ]
      break
    case 'sci-fi':
      var valoresTabela = [
        '1: Pedra do Coração: Adicione 1 CORAÇÃO ao seu máximo',
        '2: Projetor de Escudo: Item, Solte para emitir uma parede de energia PRÓXIMA com DEFESA 14 e 2 CORAÇÕES',
        '3: Torreta Sentinela: Item, Construa com Esforço, Dispara duas vezes por rodada dentro do alcance LONGO, DEFESA 12, 1 CORAÇÃO',
        '4: Célula de Fusão: Comida, apenas para MECHA, Cura 1D12, verificações de DEX e STR são FÁCEIS por 1D4 ROUNDS',
        '5: Rifle de Plasma: Arma, Mágica, Nunca precisa recarregar, Sempre causa ULTIMATE quando usado no vácuo',
        '6: Incinerador: Arma, Unidade de chamas de alta pressão, Não pode ser usada no vácuo, Ignora alvos PRÓXIMOS',
        '7: Âncora Gravitacional: Item, Um pico de gravidade que gruda com imenso poder, +10 STR em qualquer superfície',
        '8: Nano-Guincho: Item, cabo de 100 pés, Folga grátis ou enrolar, +10 STR ao puxar, O cabo tem 1 CORAÇÃO',
        '9: Armadura de Poder do Império: Armadura, +2 DEFESA, +2 STR, Use 1 de 3 combustíveis para dobrar as estatísticas por 1D4 ROUNDS',
        '10: Armadura Xill: Armadura, DEFESA +3, DEFESA +1 por ataque fracassado contra você, anula após ser atingida',
        '11: Túnicas de Zurin: Item, +2 WIS, Comando move a túnica para qualquer aliado PRÓXIMO e absorve o próximo ataque',
        '12: Lentes Cibernéticas: Item, Substitutos oculares, +1 WIS, Apenas falha em missões de reconhecimento ou observação em um 1',
        '13: Flauta de Zurin: Item, Toque por um turno para curar todos os que puderem ouvir por 1D8 OU torne a recuperação FÁCIL',
        '14: Capacete Plasteel: Armadura, DEFESA +2, Ignora qualquer efeito que possa cegar ou ensurdecer você',
        '15: Serra de Rip: Arma, Mágica, Motosserra com alimentação de fusão, ULTIMATE contra estruturas / objetos',
        '16: Espada de Íon: Arma, Mágica, Não ocupa um espaço, Altamente ocultável, ULTIMATE em 18+',
        '17: Martelo de Duranium: Arma, Indestrutível, Magnéticos fazem MAGIA quando lançados, retorna',
        '18: Micro-Jato: Item, um propulsor superpoderoso e pequeno que pode mover até 50 toneladas',
        '19: Ferramenta Omnitool Rask: Item, Útil e versátil, Qualquer Tentativa ou Verificação que poderia usar ferramentas é FÁCIL',
        '20: Unidade Remota: Item, Anexe a qualquer Arma ou Item para acionar ou usar de até 1 milha de distância',
        '21: Inseto Hacker: Item, um módulo pequeno que decodifica senhas ou abre portas trancadas em 1 rodada',
        '22: Granada de Partículas: Arma, 3 unidades, Detona instantaneamente ou com um fusível de 1 rodada, Explode causando ULTIMATE, NEAR',
        '23: Monofilamento: Item, cabo microfino para armadilhas, invisível, causa ULTIMATE quando usado como garrote',
        '24: Gel da Fera de Madeira: Comida, uma pequena bolha de geleia, cura 1D12 por 3 RODADAS, causa dor ardente',
        '25: Pílula de Poder: Comida, 3 unidades, move FAR duas vezes em um turno E realiza uma ação',
        '26: Armadura de Fumaça: Item, +2 DEFESA, só pode ser detectado por outros com um teste de procura HARD',
        '27: Cortador a Laser: Item, realiza esforço ULTIMATE contra estruturas e objetos dentro do alcance FAR',
        '28: Canhão de Arco: Arma, energia arqueada salta para um alvo, mágico, DOBRO se o alvo estiver revestido de metal',
        '29: Nano-Enxame: Item, 10.000 máquinas minúsculas penetram em pequenos espaços, realizando uma tarefa pequena',
        '30: Massa de Nitro: Item, pegajoso, explode quando é inflamado ou atingido, DOBRO DE ULTIMATE / NEAR',
        '31: Espuma Médica: Comida, 2 usos, cura até HP completo, regenera 3 HP por rodada por 1D4 RODADAS',
        '32: Queda Gravitacional: Item, berço de energia azul densa, diminui a queda de todos os objetos ou aliados NEAR',
        '33: Módulo de IA: Item, uma personalidade portátil que pode realizar testes de INT, WIS, CHA em um local',
        '34: Uniforme do Império: Armadura, +1 DEFESA, patente de capitão com arma de fogo e roupa completa',
        '35: Marca do Devorador: Item, um sinal do mal, +1 INT, intui perigo iminente com teste de INT',
        '36: Perfurador Gaussiano: Arma, agulha magnética, se você acertar, causa ULTIMATE em tiros feitos posteriormente',
        '37: Arco de Energia: Arma, mágico, sem munição necessária, escolha propriedades de raio de gelo ou fogo',
        '38: Módulo de Fogo Rápido: Item, anexado a qualquer arma de longo alcance, se você acertar, atire novamente',
        '39: Morteiro de Plasma: Arma, lança um projétil alto, impacto em 1D4 RODADAS, ULTIMATE para o alvo',
        '40: Arreio da Alma: Item, se você rolar um 6 quando MORRENDO, instantaneamente se levanta com 1 HP',
        '41: Nano Gar: Comida, cerveja infundida com Nanites, cura completamente a HP, mas falha automaticamente na próxima checagem em caso de um resultado 1.',
        '42: Lamina dos Titãs: Arma, só pode carregar outras armas quando equipado, Enorme, ULTIMATE em 15+.',
        '43: Pistola de choque: Arma, o alvo pode rolar CON para resistir, caso contrário, fica ATORDOADO por 2 ROUNDS.',
        '44: Mutação: MAGIA INT, concede uma modificação biológica menor, como guelras, barbatanas, garras ou pelos.',
        '45: Drenar: MAGIA INT, drena o ESFORÇO MÁGICO de um alvo e converte em HP.',
        '46: Ligação mental: MAGIA INT, obtém o conteúdo dos pensamentos de um alvo OU rola ULTIMATE para convencer.',
        '47: Espinho: MAGIA INT, lança um raio de energia perfurante, atinge todos os alvos em uma linha reta de até LONGE.',
        '48: Hackear: MAGIA INT, entra em qualquer sistema de computador por 2 ROUNDS, +5 INT e ULTIMATE dentro.',
        '49: Fumaça: MAGIA INT, assume a forma de fumaça por um número de ROUNDS igual à sua INT.',
        '50: Bênção do Vazio: MAGIA WIS, concede a um aliado um sucesso garantido na próxima checagem.',
        '51: Doador de vida: MAGIA WIS, dá sua vida por outra pessoa, cai para 0 HP, revive um aliado MORRENDO para a HP máxima.',
        '52: Congelar: MAGIA WIS, emite uma nuvem de frio congelante em NEAR, imobiliza inimigos por 1D4 ROUNDS.',
        '53: Ar elemental: MAGIA WIS, emite uma explosão de ar, empurra objetos e alvos com +5 FOR.',
        '54: Palma de Ferro: MAGIA WIS, seus próximos 1D4 ataques desarmados têm +3 TENTATIVA e ULTIMATE.',
        '55: Talismã de Cristal: Item, marca 1 inimigo, ataques contra esse alvo adicionam ESFORÇO MÁGICO.',
        '56: Botas Mag: Armadura, +1 DEFESA, anda em qualquer superfície metálica sem checagens de DEX.',
        '57: Hauberk de Durânio: Armadura, +3 DEFESA, ignora todos os ataques à distância que usam projéteis.',
        '58: Módulo Telecinético: Item, move objetos de até 5 libras de LONGE.',
        '59: Chip Astro: Item, todas as checagens de pilotagem, navegação espacial ou manobras são FÁCEIS.',
        '60: Óculos de Atirador de Elite: Armadura, +1 DEFESA, +5 para ataques em LONGE.',
        '61: Plataformas de Teleporte (par de 2): Item, Coloque as plataformas, blip entre elas, Ativas por 1D4 ROUNDS',
        '62: Livro das Estrelas: Item, +1 INT, Localize-se em qualquer lugar do cosmos com uma checagem de INT FÁCIL',
        '63: Livro das Luas: Item, Checagem de INT FÁCIL para saber a história de qualquer Lua no cosmos',
        '64: Livro das Bestas: Item, Faça uma checagem de WIS FÁCIL para saber detalhes sobre qualquer criatura que você veja',
        '65: Biscoito Hagro: Comida, Cura todos os aliados PRÓXIMOS a você por 1D12',
        '66: Cápsula Tentáculo: Item, Ative para invocar um TENTÁCULO GIGANTE por 1D4 ROUNDS',
        '67: Poesia Vogon, Volume 3: Item, Se lido em voz alta, as criaturas que ouvem fazem uma checagem de CON ou sofrem 1D4 de dano',
        '68: Braço Utilitário: Armadura, +2 DEFESA, Um braço hidráulico compacto, checagens de STR FÁCEIS, EQUIPA 12 espaços',
        '69: Rastreador de Movimento: Item, Enorme, Ocupa 3 espaços de equipamento, Detecta TODO movimento em DOBRO de LONGE',
        '70: Grav Bike: Item/Veículo, Uma moto micro hiper-rápida, Assentos para 2, Subsônica, Dobrável em 3 espaços de carga',
        '71: Superfaísca: Item, Dê partida em qualquer motor, hiperdrive, stardrive ou outro motor',
        '72: Bobina EM: Item, Ative em 4 ROUNDS, eletrônicos em FAR ficam desativados por 4 ROUNDS',
        '73: Armadilha Magnética: Item, Coloque para definir uma armadilha magnética, metais PRÓXIMOS ficam presos por 4 ROUNDS',
        '74: Pílula de Imunidade: Comida, +5 CON até a sua próxima refeição',
        '75: Vírus de Flash: Item, Implante um comando infeccioso e indomável em um sistema de computador',
        '76: Fugitivo: Item, Um drone robô de movimento rápido que pode recuperar ou reconhecer em um raio de meia milha',
        '77: Aranha de Reparo: Item, Regenera 1 HP por round, Repara qualquer LOOT danificado em 1D4 ROUNDS',
        '78: Bastão de Colapso: Arma, Mágica, Um bastão de metal, encolhe até 1 polegada ou se estende até o comprimento de LONGE',
        '79: Iluminador: Item, um pequeno orbe flutuante que projeta um feixe de luz branca para LONGE',
        '80: Espuma Supressora: Item, 3 usos, Suprime instantaneamente qualquer fogo em um raio de FAR',
        '81: Tijolo de Munição: Munição, Munição micronizada, 50 unidades, para qualquer arma, não ocupa espaço de transporte.',
        '82: Anulador Sonoro: Item, Anula TODO SOM em um alcance DISTANTE após a ativação, dura 1D4 ROUNDS.',
        '83: Feromônio Reptóide: Comida, Repela ou atraia forma de vida biológica com +10 CHA, dura 4 ROUNDS.',
        '84: Metralhadora de Corrente de Duranium: Arma, Mágica, Use 1D4 ROUNDS para girar, dispare 6 ataques em 1 turno.',
        '85: Cartão G: Item, 1.000 moedas de crédito.',
        '86: Ás de Stubing: Item, Um Ás de Espadas desgastado, resgatável por uma nave estelar de sucata... em algum lugar...',
        '87: Simbionte Reptóide: Item, Não pode ser removido, ganha os BÔNUS e as peculiaridades de um Reptóide.',
        '88: Coroa Xevosiana: Item, +2 CHA, inclui patente e título de um ancião Xevos.',
        '89: Pílula de Cristal: Comida, TODOS OS EFEITOS MÁGICOS são MÁXIMOS por 4 ROUNDS.',
        '90: Pedra do Coração Amigável: Adiciona 1 CORAÇÃO ao máximo de qualquer aliado.',
        '91: Barreira Hidráulica: Item, Instala em qualquer porta física, Torna-se um desafio de 3 CORAÇÕES para abrir.',
        '92: Garra Energética: Item, Anexa a qualquer objeto dentro de 2 milhas, Amarrado por 1D4 ROUNDS.',
        '93: Traje EVA: Armadura, +3 DEFESA, Respira, Imune ao fogo, radiação, frio e bioagentes.',
        '94: Anel do Sol: Item, Quando usado, qualquer dano de fogo o CURA em vez disso.',
        '95: Whiskey Gar: Comida, Cura para HP total, torna-se invulnerável por 1D4 ROUNDS.',
        '96: Pedra do Coração: Adiciona 1 CORAÇÃO ao seu máximo.',
        '97: Profecia: Feitiço INT, Se um TIMER for rolado, deduza seu significado.',
        '98: Dominar Máquina: Feitiço WIS, Controla completamente qualquer 1 máquina por 1D4 ROUNDS.',
        '99: Unidade de Dimensão de Bolso: Item, Uma porta de entrada para um reino minúsculo, contém 50 ESPÓLIOS e até 10 pessoas.',
        '100: Inversor de Polaridade: Item, Inverte FACILMENTE qualquer efeito baseado em energia com um teste INT.',
      ]
      break
    case 'epic':
      var valoresTabela = [
        '1: Pedra do Coração: Adicione 1 CORAÇÃO ao seu máximo',
        '2: Cinto do Lutador: Armadura, +1 DEFESA, Quando MORRENDO, adicione 2 ao seu rolamento',
        '3: Moedas do Rei: Ganhe 3 MOEDAS DE HERÓI que podem ser dadas a OUTROS JOGADORES por feitos heroicos',
        '4: Gema de Energia Encadeada: Item, Anexe a uma arma, Torne Mágica, Esforço atinge todos os inimigos PRÓXIMOS',
        '5: Joia de Gêmeos: Item, Sintonize com qualquer MAGIA DE INT, Essa magia é lançada duas vezes quando usada',
        '6: Pulseira de Salamandra: Item, Regenera 1 HP a cada rodada, a menos que esteja MORRENDO',
        '7: Braçadeiras de Gelo: Armadura, +3 DEFESA, Torna-se imune a qualquer dano causado ou efeitos negativos do frio',
        '8: Pedra de Afiar Ácida: Item, Afie uma arma de lâmina, ataques com essa arma destroem 1 engrenagem',
        '9: Capacete de Udin: Armadura, +4 DEFESA, +3 CAR, Aliados PRÓXIMOS a você ganham +1 DEFESA',
        '10: Anel de Invisibilidade: Item, Faça um teste de SAB para ativar, permaneça invisível por 1D4 ROUNDS',
        '11: Coroa dos Goblins: Item, Comande todos os Goblins com autoridade absoluta, mesmo que eles o odeiem',
        '12: Ilusão de Si Mesmo: MAGIA DE INT, Conjure um clone de espelho muito realista de si mesmo',
        '13: Salto Dimensional: MAGIA DE INT, Salte para qualquer local que você possa ver ou se lembrar com precisão',
        '14: Chifres da Tempestade: Armadura, +3 DEFESA, teste de SAB comanda o clima ao ar livre',
        '15: Mão da Ressurreição: Item, Revive 1 morto para HP total, role 1D4, se um 1 / 2 o item é destruído',
        '16: Urso Dire: MAGIA DE SAB, Torne-se um urso enorme por 1D4 ROUNDS, Adicione 1 CORAÇÃO, Duplique os bônus',
        '17: Pele de Ferro: MAGIA DE SAB, Sua DEFESA é 20 por 1D4 ROUNDS',
        '18: Gar Hoppy: Comida, Cure para HP total, Todos os testes são FÁCEIS por 1D4 ROUNDS',
        '19: Bomba Anã: Arma, O fusível queima por 1D4 ROUNDS, Explode causando 4D12 a PRÓXIMO',
        '20: Capuz do Medo: Armadura, +3 DEFESA, inimigos que o veem fazem um teste de SAB ou fogem na próxima rodada',
        '21: Tiara de Diamante: Item, Uma coroa que vale mais do que uma pequena cidade.',
        '22: Rosa de Marfim: Item, Conceda a uma pessoa, essa pessoa irá protegê-lo com sua vida.',
        '23: Dente do Agnar: Item, Anexado a 1 Arma, a arma causa ULTIMATE em qualquer rolagem de 15+.',
        '24: Bobina de Magma: Item, Libera fumaça e fogo para tornar a verificação de FORÇA FÁCIL ou a FORÇA ESFORÇO a definitiva.',
        '25: Botas de Sapo: Armadura, +2 DEFESA, Quando movendo longas distâncias, saltam com facilidade.',
        '26: Tabardo Heroico: Item, Quando você grita: Huzzah!, aqueles que gritam: Huzzah! rolam FÁCIL na próxima jogada.',
        '27: Canção da Montanha: Magia de INT, Cante! Inimigos em distância longa estão -5 CHA para resistir a persuasão.',
        '28: Arpão Mágico: Arma, Mágica, Ataque para agarrar um inimigo com +5 FOR se eles tentarem escapar.',
        '29: Arco da Procura: Arma, Mágica, Se souber o nome de um alvo, nunca erra o tiro.',
        '30: Cubo de Lodo de Estimação: Item, Este pequeno Cubo de Lodo se apegou a você como pai/mãe, 3” de cada lado.',
        '31: Goblin de Estimação: Item, Este pequeno e desajeitado runt jurou nunca deixar seu lado.',
        '32: Lâmina de Fogo: Arma, Mágica, +3 tentativas/esforço, Ignora inflamáveis, 1D4 por 1D4 ROUNDS.',
        '33: Onda de Fúria: Magia de SAB, Se PERTO do oceano, chame uma onda massiva, impacta em 1D4 ROUNDS.',
        '34: Inversão de Gravidade: Magia de INT, Inverta a gravidade em um alcance de distância longa por 1D4 ROUNDS.',
        "35: Elmo de Horror Cerebral: Armadura, +3 DEFESA, Ganhe a propriedade 'Mostra-lhe coisas' de um Horror Cerebral.",
        '36: Tripé de Atirador: Item, Ganhe +5 Tentativas/Esforço ao atirar em alvos além de FAR.',
        '37: Observador: Item, Um pequeno olho de vidro, coloque em qualquer lugar e veja através dele em um raio de 1 milha.',
        '38: Cheddar de Dobbs: Comida, 3 unidades, Adicione em qualquer COMIDA para dobrar seus efeitos.',
        '39: Disco de Yalfonso: Item, Um disco de energia sem atrito e levitante que suporta até 200 libras.',
        '40: Arnês de Batalha de Ramthas: Armadura, +1 DEFESA, Ganhe 3 slots adicionais em ENGRENAGEM EQUIPADA.',
        '41: Carro de Ronaldo: Item, ganhe 10 slots adicionais em equipamentos CARREGADOS',
        '42: Chamado de Aram: Item, um poderoso chifre de guerra, soa um chamado ouvido por 5 milhas, com um +3 de CHA',
        '43: Sopa Genética: Comida, transforma o comedor em uma nova forma biológica aleatória instantaneamente',
        "44: Corda Rúnica: Item, QUALQUER rolagem usando esta corda é FÁCIL, 50'",
        '45: Pedra de Thoor: Item, somente o saqueador é capaz de levantá-la ou movê-la, um cubo do tamanho de uma bola de beisebol',
        '46: Óculos de Raios Gnomos: Armadura, +2 de DEFESA, Dispara um raio de dano MÁXIMO',
        '47: Garras Selvagens: Arma, Mágica, +3 Tentativas, Lâminas retráteis, Role ESFORÇO DUAS vezes em um acerto',
        '48: Cinto de Bebedeira: Armadura, +4 de DEFESA, Nunca falhe em outro teste de CON',
        '49: Livro do Infinito: Item, Você tem uma memória perfeita de todos os fatos que já encontrou',
        '50: Amuleto do Trovão: Item, ao rolar MÁXIMO, role novamente qualquer número menor que 6',
        '51: Saco Maravilhoso de Lemninkainen: Item, aumenta seus slots de equipamentos CARREGADOS para 20',
        '52: Akintu: Item, uma estranha estátua tiki que traz boa sorte, quando você rolar um 19, trate-o como um 20',
        '53: Sanduíche Encantado: Comida, Nunca estraga, 5 mordidas, 1 mordida = 1D8 HP, Quando terminar, ganhe +1 CON',
        '54: Búfalo de Nuvem: Um corcel que desce dos céus, carrega 8 pessoas e 10 DESPOJOS',
        '55: Presa Vermelha: Arma, Grande Espada Mágica, dano que você causa com Presa Vermelha, cura metade disso',
        '56: Dardos de Cristal: Munição, 3 Contagem, Mágica, Imobiliza o alvo, em 1D4 ROUNDS explode para 2D12',
        '57: Coração da Terra: Item, um rubi maciço, a maior e mais rara jóia de todo o mundo',
        '58: Derretedor de Metal Gnomico: Item, 1D4 ROUNDS atinge o poder total, vaporiza objetos de metal PRÓXIMOS',
        '59: Armadilha de Fantasma: Item, Contém 5 seres não corpóreos: coloque, espere, ative, o Alvo faz um teste de DEX',
        '60: Armadura de Adamantium: Armadura, +8 de DEFESA, Ignora qualquer Dano abaixo de 3, Ocupa 5 slots',
        '61: Braço Mecânico: Item, Prótese, +3 FOR, todas as jogadas de FOR são FÁCEIS, -1 CAR',
        '62: Suco de Sapho: Comida, +8 INT, triplique o ESFORÇO do seu próximo FEITIÇO',
        '63: Traje de Styll: Armadura, +4 DEFESA, não use nenhuma outra armadura, respire em qualquer lugar, cure 1 HP / ROUND',
        '64: Pulseira de Thoor: Item, +2 FOR',
        '65: Anel de Agilidade: Item, +2 DES',
        '66: Cota de Malha Bêbada: Armadura, +2 DEFESA, +2 CON, nunca falhe em um teste envolvendo Garrafa',
        '67: Cristal do Sábio: Item, +2 INT',
        '68: Efígie de Osric: Item, +2 SAB',
        '69: Gorjal Cintilante: Armadura, +1 DEFESA, +2 CAR',
        '70: Adaga do Invisível: Arma, Mágica, se o ataque for indetectado, alvo do tamanho humano cai a 0 HP',
        '71: Pá do Carrasco: Arma, Mágica, em um 20, decapite qualquer alvo do tamanho humano',
        '72: O Oculto: FEITIÇO DE INT, Aliados PRÓXIMOS ficam invisíveis por 1D4 ROUNDS, ficando visíveis se se afastarem',
        '73: Elmo do Matador: Armadura, +2 DEFESA, +6 Esforço de Armas',
        '74: Olho de Idimmu: Item, Amuleto, +6 Esforço Mágico',
        '75: Benção dos Deuses: Item, conceda a um OUTRO JOGADOR uma Recompensa de Marco de sua escolha, um uso',
        '76: Cogumelo Timecap: COMIDA, PULE a próxima rodada do DM',
        '77: Role duas vezes na tabela de DESPOJOS ANTIGOS',
        '78: Raio Redutor: FEITIÇO DE INT, Reduza um alvo a 1/100 de seu tamanho por 1D4 ROUNDS',
        '79: Crescimento Gigante: FEITIÇO DE SAB, aumente o tamanho de um alvo em 5x por 1D4 ROUNDS',
        '80: Muralha Escudo de Osric: FEITIÇO DE SAB, forme uma enorme muralha de castelo com pedregulhos ou calçamentos',
        '81: Destrua os Mortos: FEITIÇO DE INT, Aniquila 1 morto-vivo por 1 HP queimado, alcance LONGO',
        '82: Navio Fantasma: Item, Conjure um galeão negro, sem tripulação, que durará 1D4 semanas antes de dissipar',
        '83: Sangue de Dragão: Comida, cresça asas e respire fogo por 1D4 ROUNDS',
        '84: Gungnir: Arma, Mágica, Lança, Passe julgamento final, +10 CHA por 1 milha',
        '85: Porta Cósmica: Item, Abra uma porta, acesse QUALQUER mundo no cosmos, 8 HP para atravessar',
        '86: Invulnerabilidade: FEITIÇO DE SAB, Unge o alvo com um toque, não pode ser prejudicado por 1D8 ROUNDS',
        '87: Sherherezazahd: Item, Uma espada fantasmagórica, adiciona Esforço de Arma Mágica a todos os ataques',
        '88: Portal Temporal: Item, Acesse QUALQUER tempo no local atual, envelheça 10 anos para atravessar',
        '89: Gar Fedorento: Comida, Libera um arroto venenoso, Reduz uma criatura PRÓXIMA a 1 CORAÇÃO',
        '90: Caminhante da Vida: Item, Deixa um rastro de flores onde quer que vá, aqueles dentro se curam em 2 HP por ROUND',
        '91: Martelo do Inferno: Arma, Mágica, TODO ESFORÇO com essa arma afeta todos os inimigos PRÓXIMOS',
        '92: Asas de Gabriel: Armadura, +5 DEFESA, Dobrável, Voe à vontade, 2X sua distância máxima de movimento',
        '93: Poço dos Desejos: Item, Imóvel após o uso, Faça 1 DESEJO por ANO, se torna realidade em 1D4 dias',
        '94: Livro da Maestria: Item, 3 páginas, Aprenda 1 Recompensa de Marco por página',
        '95: Estrela de Unadai: Comida, Ganhe +1 para todas as CARACTERÍSTICAS',
        '96: Visão da Perfeição: Armadilha, Revela a um ser MAL, teste de CHA DIFÍCIL ou ele se torna BOM',
        '97: Água da Vida: Comida, Morra, Retorne à vida 1D4 ROUNDS depois com 2 CORAÇÕES adicionais',
        '98: Hidromel de Udin: Comida, Todos que bebem acordam no dia seguinte com um CORAÇÃO adicional',
        '99: Escudo dos Anjos: Armadura, +6 DEFESA, Você e todos os aliados PRÓXIMOS ignoram qualquer dano de 5 ou menos',
        '100: Necronomicon: Item, Crie 1 FEITIÇO DE INT / FEITIÇO DE SAB com INT DIFÍCIL',
      ]
      break
    case 'bizarre':
      var valoresTabela = [
        '1: Tradutor Tênia: Item, Aumenta o apetite, Fala e compreende todas as línguas faladas',
        '2: Boneca sua: Item, Perfeitamente semelhante ao dono, Teste de INT para fazer qualquer pergunta a ela e obter uma resposta verdadeira',
        '3: Raiz de Macaco: Comida, 1 Uso, +5 DEX por 4 ROUNDS, Faça barulhos de macaco quando tentar falar',
        '4: Pássaro Corredor Sedado: Item, Pássaro sonolento foi drogado e fica fora de controle quando acorda',
        '5: Chicote Bumerangue: Arma, Um chicote de couro de 12 pés que pode ser lançado e recolhido novamente',
        '6: Anel Finful: Item, +1 DEFESA, Um anel rodeado de barbatanas tremulantes. Nade a três vezes a velocidade normal',
        '7: Saco de Dedos: Item, Um saco de couro cheio de 2D20 dedos de várias formas de vida',
        '8: Chapéu de Cabeça de Lagarto: Armadura, +1 DEFESA, Um chapéu de couro feito para se parecer com um lagarto, Convincente',
        '9: Barril de Cerveja Dud: Comida, 5 usos, Gar que foi fermentada de forma errada e não tem álcool',
        '10: Gar de Cogumelo: Comida, 5 usos, Gar fermentada com fungos. Brilha ligeiramente / delirante por 1D4 horas',
        '11: Armadilha Pegajosa: Item, Uma bola de massa ultra-pegajosa. Quando tocada, apenas um teste DIFÍCIL DE FORÇA pode libertá-lo',
        '12: Bola de Olho: Item, Um brinquedo maluco e energético de olho saltitante. Veja através dele com um teste de INT',
        '13: Prancha de Piada: Item, Uma prancha de madeira para construção, mas feita oca para quebrar com pouca força',
        '14: Lâmina do Ceticismo: Arma, Armadilha, teste DIFÍCIL DE FORÇA para guardar, Espada falante duvida de cada movimento',
        '15: Ovo Gigante: Item, Use calor e tempo para chocar. Gere 1 monstro aleatório, se liga a você',
        '16: Orelhas de Eargantua: Item, Um par de orelhas gigantes que podem ser usadas, só falha em um teste de audição com 1',
        '17: Banjo Soggy Bottoms: Item, Um instrumento de cordas estranho, entretenha qualquer pequena multidão',
        '18: Dados de Sangue de Azael: Item, Jogue esses dados vermelhos. Inimigos fascinados por eles por 1D4 ROUNDS',
        '19: Armadilha Bowby: Arma, Arco gag, quando disparado age contra o usuário, e a flecha volta',
        '20: Crânio Tagarela: Item, Um crânio humano que simplesmente não para de falar. Se descartado, aparecerá em outro lugar.',
        '21: Vestes de Kazghat: Armadura, +2 DEFESA, Imune a efeitos causados por viagem no tempo/distorção.',
        '22: Tubo do Tempo: Item, Um pequeno tubo. Passe o item através dele. Ele chegará ao passado no momento escolhido.',
        '23: Bacon da Beleza: Comida, 3 usos, aproveite +10 CARISMA por 1D4 ROUNDS. Você parece e cheira delicioso.',
        '24: Barata Bomba: Item, Um inseto mecânico. Coloque-o em movimento, ele explodirá enquanto corre em 1 TURNO.',
        '25: Sanduíche do Amor: Comida, 1 uso, quem comer se apaixona por uma pessoa de sua escolha.',
        '26: Faber Mortiferum: Livro, pergunte ao GM qualquer pergunta com INT DIFÍCIL, receba uma resposta honesta.',
        '27: Túnica da Generosidade: Armadura, +5 DEFESA, Nat 20 remove, obrigado a dar equipamentos aos amigos.',
        '28: Bota do Grim: Item, Use em uma corda ou linha para pescar, você tem garantido uma captura importante.',
        '29: Corda em Nó: Item, Um comprimento de corda de 300 pés emaranhado em nós inextricáveis.',
        '30: Toalha Verde: Item, Uma toalha verde.',
        '31: Navio em Garrafa: Item, 1 uso, quebre a garrafa para revelar um galeão completo, armas e suprimentos.',
        '32: Olho da Morte: Item, uma esfera de cristal, olhe dentro para ver o momento da sua morte.',
        '33: Aranha de Sangue: Item, aranha rasteja em você, cura 1 HP por ROUND a menos que você esteja MORRENDO.',
        '34: Seda Espectral: Item, um rolo de tecido liso que se contorce com uma infinidade de cores vibrantes.',
        '35: Parasita Planador: Item, Artrópode, FOR DIFÍCIL para remover, permite que você plane quando cair.',
        '36: Tocha Me Veja: Item, uma tocha que queimará enquanto pelo menos 1 pessoa estiver olhando diretamente para ela.',
        '37: Cubo de Slime Expansível: Item, um pequeno cubo de slime que cresce continuamente depois de liberado.',
        '38: Vento de Saras: Item, uma garrafa de ar, que sopra como vento sempre que descorcada.',
        '39: Tectura Infinitessema: Item, um calabouço minúsculo, malévolo e consciente.',
        '40: Nota para Mim: Item, uma carta escrita por você em uma dimensão alternativa, endereçada a você.',
        '41: Mão esquerda de Martin: Item, Esta é a mão esquerda de Martin. Martin quer de volta.',
        '42: Banquinho Pequeno: Item, Um vaso sanitário totalmente funcional, com 2 polegadas de altura.',
        "43: Aro do Mágico: Item, Um anel de aço que pode 'engatar' em qualquer outro anel ou círculo com um golpe.",
        '44: Frasco de Lágrimas de Demônio: Comida, 1 uso. Tome a forma de um demônio por 1D4 dias.',
        '45: Braço de Caranguejo: Armadura, DEFESA +2. Uma garra de caranguejo que se prende permanentemente ao seu ombro.',
        '46: Bicho-da-Seda Envasado: Item, Um pote contendo um bicho-da-seda. Produz 1 pé de fio inquebrável por dia.',
        '47: Pinhata de Barata: Item, Um globo de papel contendo 10.000 baratas famintas.',
        '48: Lanterna de Sett: Item, Uma lanterna acesa por vela. Quando acesa, emite escuridão absoluta por perto.',
        '49: Pau Feio Pra Caramba: Arma, Inflija 5 ou mais de dano em um alvo e dê a ele -5 de CAR permanentemente.',
        '50: Mãos Garradas: Armadura, DEFESA+1. Suas mãos têm 10 dedos, cada um funcionando como duas mãos.',
        '51: Esporos de Chang: Item, Um pote de esporos. Inalados, aumentam a acuidade do olfato em 1.000 vezes.',
        '52: Saco de Chaves: Item, Cada vez que você coloca a mão, tira uma chave. 5% de chance de ser a chave que você quer.',
        '53: Pegadas Portáteis: Item, Coloque pegadas de papel fino em qualquer lugar, elas parecem perfeitamente realistas.',
        '54: Xilofone: Item, Um instrumento musical de osso. A música pode fazer alguns homens desejar a morte.',
        '55: Incenso em Corda: Item, 5 usos. A fumaça deste incenso pode ser escalada e dura 1D4 ROUNDS.',
        '56: Flauta do Amanhecer: Item, Flauta mágica. Quando tocada com um CHA, o sol nascerá.',
        '57: Mini Mimic: Item, Um mini mimico que pode imitar qualquer objeto do tamanho de um melão ou menor.',
        '58: Carne Enforcada: Comida, 1 uso. Quando consumido, este jerky sufoca e faz o comedor desmaiar.',
        '59: Toot Cômico: Item, Anexe esta borla a um chapéu. Causa risos para quem a vê.',
        '60: Peneira de Todas as Coisas: Item, Uma peneira culinária. As coisas dentro dela se transformam em outras coisas.',
        '61: Dentes de Krynn: Item, um colar de 8 dentes de bestas, cada um ainda com fome de sua presa favorita.',
        '62: Esmeralda Faminta: Item, uma esmeralda com uma boca difícil de perceber. Ela come MOEDAS quando possível.',
        '63: Aqui, Peixinho, Peixinho: Item, um simples chifre. Quando usado, convoca um peixe de QUALQUER massa de água.',
        '64: Chapéu Aconchegante: Armadura, DEFESA +2, este chapéu de pele fofa é tão quente e aconchegante, tornando-se imune ao frio.',
        '65: Anel Seco: Item, você nunca pode ficar molhado ou tocado por líquido.',
        '66: Fissura Portátil: Item, coloque esta rachadura em um objeto e ele ficará rachado.',
        '67: Pedra Esponja: Item, uma pedra que pode absorver até 100 galões de líquido.',
        '68: Anel de Espelhos: Item, quando usado, interaja com objetos e estruturas como se estivessem invertidos.',
        '69: Pelotas de Sapo: Item, manchas verdes. Quando em contato com a umidade, cada uma se transforma em um sapo D20.',
        '70: Isca de Insetos: Comida, 3 usos, insetos dentro de 1 milha são atraídos por ela.',
        '71: Poder Errático: Um estranho raio de energia salta à frente! Um personagem aleatório recebe 2 pontos de STAT.',
        '72: Mapa Dimensional: Item, desenrole este mapa. Torna-se uma versão 3D e em movimento dos arredores.',
        '73: Óculos Voláteis: Armadura, DEFESA +1, quando rolar ULTIMATE, role duas vezes. Se sair 1, anule ambas.',
        '74: Mão em um Pau: Item, pode ser usado para abrir baús ou portas, ou testar itens armadilhados.',
        '75: Vinho de Dragão: Comida, 3 usos, após beber, você soa, cheira e intimida como um Drake.',
        '76: Baterista Macaco: Item, quando colocado, começa a tocar um tambor pequeno. Para quando guardado.',
        '77: Coleção de Tatuagens: Itens, um pequeno baú de pirata cheio de pedaços de pele tatuada.',
        '78: Tesouro de Borracha: Itens, uma coleção de moedas falsas, joias e bugigangas feitas de resina.',
        '79: Trança da Morte: Arma, uma enorme trança de cabelo que chicoteia e se move como uma ARMA, MÁGICA.',
        '80: Vórtice em uma Garrafa: Item, um poderoso vórtice em vidro. Se liberado, suga tudo LONGE.',
        '81: Larry: Item, Uma criatura pequena que lhe deve a vida. Não pode ser determinado o que ele é.',
        '82: Coco Terrivel: Item, Um coco horrível que se assemelha a um rosto humano.',
        '83: Se jogando em ALFHEIM, role uma vez na tabela de itens SCI FI.',
        '84: Se jogando em WARP SHELL, role uma vez na tabela de itens ANCIENT.',
        '85: Sangue de Deus: Comida, 1 uso, aumenta qualquer STAT em 2.',
        '86: Roda-Móvel: Veículo, 1 CHUNK, um gadget de uma roda que pode transportar até 5 passageiros.',
        '87: Pássaros da Barba: Item, uma família de pássaros que vivem na barba mais próxima, mas se movem para segui-lo.',
        '88: Abelhas: Abelhas. Muitas abelhas. Milhares de abelhas. Essas abelhas estão furiosas.',
        '89: Prancha Magnética: Item, uma prancha de madeira para construção, mas com uma força magnética de +5 STR.',
        '90: O Melhor Tabaco Conhecido: Comida, 10 usos, simplesmente o melhor tabaco do universo.',
        '91: Semente de Membro: Comida, 1 uso, aplicada a um membro amputado ou stump para crescer um novo membro em 1D4 dias.',
        '92: Uma Única Verdade: 1 uso, Diga ou descreva uma única Verdade, qualquer Verdade. Agora é verdade.',
        '93: Alma de um Rei: Item, uma centelha brilhante em vidro. Esta é a alma eterna de um rei há muito perdido.',
        '94: Bandeira da Infinitude: Item, uma enorme bandeira ondulante que pode exibir qualquer coisa que você escolher.',
        '95: Cubo de Kelligan: Item, um quebra-cabeça cúbico. Os cubos se alinham em cores e símbolos, dobrando a realidade.',
        '96: Pele Suit: Armadura, um terno de couro que se encaixa sob sua armadura, concedendo-lhe 10 HP descartáveis.',
        '97: Varinha dos Gêneros: Item, com um toque, muda o gênero de qualquer criatura.',
        '98: Caixa Fria: Item, um pequeno baú. Por dentro, está sempre frio congelante.',
        '99: Estrada Dobrável: Item, desdobre 1 milha de estrada de largura de vagão em qualquer local.',
        '100: Role duas vezes nesta TABELA.',
      ]
      break
    case 'ghost-mountain':
      var valoresTabela = [
        '1: Veneno de Cascavel, COMIDA, 5 usos, use como antídoto OU veneno.',
        '2: Crucifixo de Prata, ITEM, receba metade do dano de quaisquer entidades sobrenaturais que possam prejudicá-lo.',
        '3: Garrafão de Moonshine, COMIDA, 10 usos, 1 gole te embriaga, use como inflamável ou antisséptico.',
        '4: Pá do Coveiro, ARMA, se você reduzir um alvo a 0 HP com isso, ele MORRE instantaneamente.',
        '5: Manta de Sela, DEFESA +3, coloque em qualquer animal, todos os rolls com esse animal são FÁCEIS.',
        '6: Pulseira de Ossos dos Dedos, ITEM, rolls para controlar, destruir ou resistir a ESQUELETOS são FÁCEIS.',
        '7: Colar de Sete Presas, ITEM, se causar 5 ou mais de dano com uma FACA, role o dano novamente.',
        '8: Hepawa Warbonnet, DEFESA +1, uma coroa de penas, +5 CHA ao interagir com os Hepawa.',
        '9: Pistola Oculta, ARMA, 1 tiro, recarga de 1 TURNO, apenas utilizada de PERTO, o alvo rola SAB para detectá-la.',
        '10: Balas de Prata, MUNIÇÃO, MÁGICA, 6 contagens, causam o dobro de dano contra criaturas sobrenaturais.',
        '11: Medalhão Faminto, ITEM, ganhe o benefício máximo da COMIDA consumida.',
        '12: Mosquete Mestre, ARMA, com uma TENTATIVA de 10+, cause dano máximo, 2 TIROS, 2 TURNOS para recarregar.',
        '13: Sobretudo Blindado, DEFESA +3, tiros de LONGA distância causam apenas 1 ponto de dano.',
        '14: Cordas de Porco, ITEM, qualquer objeto, animal ou pessoa amarrados com essas cordas NÃO podem se soltar.',
        '15: Tabaco de Manteiga e Rum, COMIDA, 3 usos, pergunte ao GM qualquer pergunta e receba uma resposta verdadeira.',
        '16: Armadura de Osso de Canuska, DEFESA +5, todos os rolls ao interagir com os Canuska são FÁCEIS.',
        '17: Crânio Negro, ITEM, nenhuma entidade maligna pode chegar PERTO desse objeto poderoso.',
        '18: Algemas Enferrujadas, ITEM, prenda uma pessoa pelos tornozelos, em um roll de FORÇA DIFÍCIL, ela pode se libertar.',
        '19: Bolo de Ferro, ARMA, LONGA distância, alvos atingidos rolam DEX DIFÍCIL ou caem de bruços, imóveis por 1D4 ROUNDS.',
        '20: Clava de Mandíbula, ARMA, MÁGICA, quando atingido, alvos também perdem 3 FOR por 4 ROUNDS.',
        '21: Botas Viper, DEFESA +1, Você não pode ser envenenado, essas botas também são à prova de fogo e ácido.',
        '22: Colete do Jogador, ITEM, Um colete com bolsos escondidos, EQUIPE 15 peças de EQUIPAMENTO, 5 secretamente.',
        '23: Machado de Obsidiana, ARMA, ARREMESSÁVEL, Rerrolle os dados de DANO abaixo de 5, e escolha o melhor resultado.',
        '24: Facas de Chifre, ARMA, MÁGICA, Faça o dobro de ESFORÇO contra animais, madeira ou pedra.',
        '25: Os Dados do Diabo, ITEM, Rerrolle qualquer dado 1 uma vez por TURNO, seja compelido a fazer a vontade de Lúcifer.',
        '26: Lanterna Química, ITEM, Uma lâmpada de enxofre e magnésio, ilumina até o dobro de DISTÂNCIA.',
        '27: Luneta, ITEM, +3 de SAB ao rolar para espionar, navegar ou encontrar.',
        '28: Sabre da Cavalaria, ARMA, RARA, Alvos atingidos por 8 ou mais de DANO rolem CON ou caiam para 0 HP.',
        '29: Frasco de Clorofórmio, COMIDA, 3 usos, Respire isso para parecer morto por 1D4 horas.',
        '30: Pacote de TNT, EXPLOSIVO, Fusível de 1D4 RODADAS, Inflige 4D12 de dano a todos os ALVOS PRÓXIMOS.',
        '31: Amigo do Ferreiro, ITEM, Todos os dados ao reparar, construir ou usar ferramentas são FÁCEIS.',
        '32: Ferradura da Sorte, ITEM, Qualquer dado natural de 18+ conta como um sucesso CRÍTICO.',
        '33: Uísque Olho Vermelho, COMIDA, 5 usos, quem sabe o que isso fará com você.',
        '34: Óleo de Cobra, COMIDA, 3 usos, cura qualquer CONDIÇÃO.',
        '35: Kit de Arma Arcana, ITEM, Anexe a 1 arma de fogo, essa arma agora é MÁGICA.',
        '36: Ficha de Poker da Sorte, ITEM, Ao usar cartas, compre duas vezes e escolha o melhor.',
        '37: Kit de Bandagem de Pano, ITEM, Cure 1 HP quando tiver sucesso em: não morra em mim, cara!.',
        '38: Suco de Cacto, COMIDA, 5 usos, Substitui 1 dia de PROVISÕES para um grupo de pessoas.',
        '39: Espingarda de Cano Serrado (ARMA, Veja a lista de armas)',
        '40: Máscara da Morte, DEFESA +2, Bronze moldado em um rosto, aterrorize os habitantes da cidade, 3 de dano se removida.',
        '41: Totem do Lobo, ITEM, Lobos são atraídos por você e consideram você um deles',
        '42: Chicote de Espinhos, WEAPON, Um chicote agarrador que também pode ser usado como arma',
        '43: Arpão de Canhão, WEAPON, Funciona como um RIFLE DE ELEFANTE, agarra o alvo por 4 ROUNDS',
        '44: Anel de Rubi, ITEM, Vale 2.000 COINS, Use para hipnotizar ou enfeitiçar os gananciosos',
        '45: Robe de Cânhamo Ebon, ITEM, Não pode ser cortada, queimada, rasgada ou danificada de qualquer forma',
        '46: Broche de Marfim, ITEM, Um retrato antigo, dê a alguém para vinculá-lo a um JURAMENTO para sempre',
        '47: Katana de Aço Verde, WEAPON, RARO, AFIADO, Qualquer inimigo morto concede sua ALMA a você',
        '48: Martelo do Juiz Pendurado, ITEM, Aponte e bata, todos aqueles à vista veem o alvo como CULPADO',
        '49: Faixa Cossaca, ITEM, Seja evitado por bandidos, criminosos e foras-da-lei que possam ver a faixa',
        '50: Amuleto de Azael, ITEM, IMUNE a ataques de Azael, ele sabe sua localização',
        '51: Safira Deslumbrante, ITEM, Vale 10.000 COINS, Pode ser negociada por duas vezes o seu valor',
        '52: Garfo do Diabo, WEAPON, MÁGICO, Lança, Pode ser consumido pelas chamas sob comando',
        '53: Caco de Obsidiana Afiado, ITEM, Substitua a lâmina em uma WEAPON, torna-se tão mortal quanto uma arma de fogo',
        '54: Hamburguer de Urso, FOOD, 3 usos, +5 STR por 4 ROUNDS, Cura para HP total',
        "55: Barra de Gordura, ITEM, Aplique em qualquer superfície para torná-la super escorregadia, inflamável e à prova d'água",
        '56: Farol do Inferno, ITEM, Todos os demônios e infernais dentro de 1 milha são atraídos por ele até ser guardado',
        '57: Zarabatana, WEAPON, SILENCIOSA, Inclui 8 dardos, VENENA um alvo sem detecção',
        '58: Sobretudo do Range Rider, DEFESA +1, Use metade de SUPRIMENTOS, Todos os rolagens montadas são FÁCEIS',
        '59: Chave Esquelética Verdadeira, ITEM, Abra QUALQUER porta trancada',
        '60: Tapa-Olho de Caveira Cruzada, ITEM, Sob comando, você tem visão limitada do tipo RAIO-X para LONGE',
        '61: Luvas de Briga, WEAPON, Lute desarmado como se tivesse uma WEAPON, DEFESA +3',
        '62: Laço Dourado, ITEM, MÁGICO, Qualquer alvo preso deve dizer a verdade, imobilizado',
        '63: Bolsa de Poeira de Ouro, ITEM, 1 uso, Polvilhe em qualquer objeto para torná-lo MÁGICO',
        '64: Garrafa de Água Benta, FOOD, 3 usos, Polvilhe em um limiar, o mal sobrenatural não pode passar',
        '65: Espada-Bengala, WEAPON, Requer um teste de WIS DIFÍCIL para ser detectada',
        '66: Almanaque Hexar, LIVRO, Um livro massivo de ritos mágicos, aprenda e conjure 5 SPELLS de qualquer tipo',
        '67: Balas de Fumaça, AMMO, 12 unidades, Essas balas atingem alvos com a condição de SMOKE',
        '68: Urna dos Anjos, ITEM, Queime uma criatura morta, coloque suas cinzas aqui, ela renascerá em 1D4 dias',
        '69: Mochila do Espreitador, ITEM, Faça um teste de WIS uma vez por localização, encontre um objeto que procura lá',
        '70: Anel dos Matadores, ITEM, Em um ataque com rolagem de 15+, role novamente, se a segunda rolagem acertar, ela faz esforço SUPREMO',
        '71: Bichinho Precisando de Ajuda, ESPECIAL, Você encontra um animal pequeno que se apega a você como seu melhor amigo',
        '72: Pedra de Afiar de Diamante, ITEM, Afiar uma WEAPON com lâmina, essa WEAPON recebe +3 EFFORT',
        '75: Medalhão em Espiral, ITEM, O esforço feito com SPELLS SAGRADAS é +3',
        '76: Selo do Justo, ITEM, Concede a você a adesão ao culto elite de pistoleiros',
        '77: Aliança de Casamento de Ezra, ITEM, O fantasma de Ezra assombra você para sempre, role um 20 natural para removê-lo',
        '78: Adaga das Ruínas, WEAPON, Faz o TRIPLO do ataque SUPREMO contra estruturas, portas ou veículos',
        '79: Cajado dos Espíritos, ITEM, MÁGICO, Aprenda e conjure 5 SPELLS de WIS de qualquer tipo',
        '80: Tambor Fantasma, INSTRUMENTO, MÁGICO, Entidades sobrenaturais são aterrorizadas por esse som',
        '81: Bolsa de Dinheiro, ITEM, Contém 5d10 x 1.000 MOEDAS em títulos, dinheiro e ouro',
        '82: Pêssegos do Cacto Azul, FOOD, 2 usos, Cura 1D12 HP, Cura todas as CONDIÇÕES',
        '83: Revólver Espada Negra, WEAPON, MÁGICO, Nunca precisa de MUNIÇÃO',
        '84: Garra de Corvo, ITEM, Transforme-se em um corvo com um teste de WIS, permaneça pelo tempo que escolher',
        '85: Flechas de Bala, AMMO, 20 unidades, Use as regras de arma de fogo ao disparar com um arco',
        '86: Baralho do Demônio, ITEM, Substitui o baralho de jogadores, Trate cada carta como se fosse uma carta melhor',
        '87: Baralho do Diabo, ITEM, Substitui o baralho de jogadores, Jogue novamente em qualquer carta que não seja de figura',
        '88: Turbante dos Futuros, ITEM, Com um teste de INT DIFÍCIL, veja em um futuro específico',
        '89: Picareta Dourada, ITEM, Faça um teste de WIS subterrâneo, encontre um fragmento de YOG, pepita de ouro ou túnel',
        '90: Machado de Azael, WEAPON, MÁGICO, Quando atinge um alvo, eles rolam CON ou caem para 0 HP',
        '91: Baú das Maravilhas, CHEST, Faça 3 rolagens de LOOT, que podem ser roladas em qualquer TABELA',
        '92: Cocar de Coruja, DEFESA +5, Você não pode ser ferido por WEAPONS de lâmina',
        '93: Garra de Corrente, ITEM, Com um teste de DEX, voe para qualquer ponto DISTANTE instantaneamente',
        '94: Máquina Incrível do Dr. Warstein, ITEM, esta máquina assume uma forma designada pelo GM',
        '95: Arma Fantasma, WEAPON, MÁGICO, Esta pistola não pode errar e nunca precisa ser recarregada',
        '96: Bobina de Relâmpago, ITEM, Use a alavanca, 1D4 ROUNDS tudo dentro de DISTANTE sofre 3D12 de dano',
        '97: Cruz de Santiago, ITEM, SPELLS INFERNAIS não podem prejudicá-lo',
        '98: Gueras Malefectorum, LIVRO, Ataques corpo a corpo em Infernais são CRÍTICOS e MÁGICOS',
        '99: Balas Fantasmas, ITEM, 20 unidades, Dispare através de qualquer material até DISTANTE',
        '100: Anel das Estrelas Cadentes, ITEM, Faça um desejo. Ele se tornará realidade. Pode haver consequências',
      ]
      break
    case 'magic':
      var valoresTabela = [
        '1: Bastão de Caminhada, Item, Move-se LONGE e ainda realiza uma ação.',
        '2: Espelho de Feitiço, Item, Reflete um FEITIÇO lançado contra você em uma direção aleatória com uma rolagem de INT.',
        '3: Coroa do Olho, +1 DEFESA, O usuário desta faixa refrativa não pode ser pego de surpresa.',
        '4: Manual de Persuasão, Ferramenta, +3 CHA em qualquer TENTATIVA que utilize linguagem ou discurso.',
        '5: Pedra de Sangue, Item, Rola DIFÍCIL, se você tiver sucesso, pague 1 nível a menos do que o CUSTO DE PODER.',
        '6: Portador da Noite, Adaga, Qualquer vítima ferida por esta lâmina MÁGICA fica cega por 1D4 ROUNDS.',
        '7: Armadilha do Profeta da Destruição, Armadilha, Disparada com fio comum, Libera APOCALÍPTICA no PODER 4.',
        '8: Adaga de Gelo, Faca Kris, Se ferido com 6+ de dano com esta lâmina, congelado sólido por 1D4 ROUNDS.',
        '9: Óculos Vermelho Tintos, Item, Se você vir um objeto primário vermelho, incendeie esse objeto com uma rolagem de INT.',
        '10: Giroscópio da Queda, Item, Ao cair, role CON para mudar seu campo gravitacional por 1 ROUND.',
        "11: Fragmentos de Ka'a, 3 Pontas de Flecha, Uma ponta de flecha que explode por DOBRO DO ULTIMATE no impacto.",
        '12: Proto Artefato, Item, 2 Usos, Alcance este objeto estranho e retire 1 SAQUE aleatório.',
        '13: Manto da Criatura, +2 DEFESA, Torne-se um pequeno animal, +5 DEX, permaneça ou volte a qualquer momento.',
        '14: A Tempestade da Aurora, Cajado, Use DEX para lançar qualquer FEITIÇO de ataque a distância no PODER 1 por 2 pontos de SP.',
        '15: Flauta do Esquecimento, Instrumento, Toque uma melodia, os ouvintes esquecem onde estão por 1D4 ROUNDS.',
        '16: Chinelos de Madeira do Zeke, +1 DEFESA, Confortáveis, sempre adicione um extra de +3 às suas rolagens de RECUPERAÇÃO.',
        '17: Giz de Porta, Item, 3 usos, Desenhe uma porta, ela leva a outra porta... em qualquer lugar.',
        '18: Prisão de Espelho, Item, Armadilha, Veja o seu reflexo e fique preso por 1D4 ROUNDS.',
        '19: Luvas Ladrão de Feitiços, +2 DEFESA, Com uma rolagem de DEX, roube um FEITIÇO lançado em você no último ROUND.',
        '20: Chapéu de Presto, +2 DEFESA, Uma vez por local, retire um SAQUE BIZARRO.',
        '21: Frasco de Fadas de Chamas, Item, 10 Fadas, bolas de fogo voando rápido com 1 HP que lutam por você',
        '22: Varinha de Desarmamento, Varinha, Dispare em um inimigo que você vê com DEX para enviar sua ARMA voando',
        '23: Matador de Dragões, Lança, ALCANCE NEAR, ÚLTIMO, dano de 8+ natural explode vs. dragões',
        '24: Filactério, FEITIÇO, Armazene sua alma imortal em um objeto pequeno. Se o objeto estiver intacto, você não pode morrer',
        '25: Ouvido de Garland, Item, Um chifre de ouro que permite que você ouça TUDO dentro de 1 milha',
        '26: Tecido de Sombras, +2 DEFESA, Crie uma peça de vestuário. Rolagem INT, fique perfeitamente plano, qualquer cor',
        '27: Fogos de Artifício de Dragão, Item, 5 Usos, Surpreenda uma aldeia de pessoas em admiração ou alegria entusiasta',
        '28: Xadrez Fantasma, FEITIÇO, Controle 1D6 inimigos como se fossem peças em um tabuleiro por 1D4 RODADAS',
        '29: Esfera de Projéteis, FEITIÇO, Crie uma esfera de cristal. Projéteis atraídos por 1D6 RODADAS',
        '30: Kit de Poções, Ferramentas, Faça poções com um único INGREDIENTE RARO em vez de 3',
        '31: Anel da Sorte de Ingara, Item, 6 Usos, Transforme uma rolagem falha em um sucesso',
        '32: Trombeta do Arauto, Item, 2 Usos, Chame um Anjo para lutar ao seu lado por 1D4 RODADAS',
        '33: Bastão de Adesividade, Bastão, Transforme qualquer objeto em madeira sólida por 1D4 RODADAS',
        '34: Arcanum Caleidoscópico, Livro, Páginas se alinham de maneiras cósmicas. Responda qualquer pergunta sobre cor',
        '35: Pergaminho da Vergonha, Pergaminho, Uma criatura que você vê fica instantaneamente atordoada e envergonhada',
        '36: Simbionte de Cristal, Item, +8 DEFESA, Um cristal verde que paira PERTO para interceptar ataques',
        '37: Disco de Esticamento, Item, Gire este disco e estique um alvo que você vê duas vezes o seu comprimento',
        '38: Amuleto de Dragões, +1 DEFESA, Nenhum dragão pode prejudicá-lo enquanto estiver usando este talismã',
        '39: Amuleto de Garland, Item, Para uma rolagem em que você não recebe um bônus, receba +2 para essa rolagem em vez disso',
        '40: Raiz de Mana, Comida, 3 usos, Consuma para conceder 10 HP utilizáveis apenas para absorver o CUSTO de lançamento de FEITIÇO',
        '41: Mecanismos de relógio, Item, Use magia de cura em seres mecânicos como se estivessem vivos',
        '42: Kreel de cogumelo de vime, Item, Contém 15 INGREDIENTES RAROS',
        '43: Vela fantasma, Item, 5 usos, Acenda esta vela para atrair e revelar FANTASMAS dentro de 1 milha',
        '44: Hurdy Gurdy do Hino de Olfan, Instrumento, Conjura qualquer MAGIA que fortaleça aliados sem custo',
        '45: Dente do Lasher, Item, Você está sempre parcialmente desmaterializado, qualquer rolagem para evitar um ataque é sempre FÁCIL',
        '46: Sino respiratório, Item, Um sino de mergulho que permite que 3 pessoas respirem em qualquer ambiente sem ar',
        '47: Estrela de Aras, Arma, Uma glaive que causa dano a múltiplos inimigos e retorna',
        '48: Crânio de Bruxa, Item, Revele sua face para soltar um grito aterrorizante, Role CAR para resistir ao medo',
        '49: Maça de corrente Krellian, Arma, Uma bola pontiaguda enorme em 8 pés de corrente, +6 ESFORÇO DE ARMA',
        '50: Vara cerebral Gnomica, Varinha, Altere sua voz, iluminação e ruídos para confundir aqueles que veem',
        '51: Vara de podridão, Varinha, Aflige uma estrutura com musgo, mofo e decadência. Colapsa em 1D4 dias',
        '52: Espada Morta, MÁGICA, Fantasmas, espectros e aparições seguem seus comandos, ainda te odeiam',
        '53: Sangue de um Archfiend, 12 INGREDIENTES RAROS que podem ser usados para fazer POÇÕES',
        '54: Máquina de escudo Iradrum, Item, Um escudo consciente. Absorve 20 de dano por localização',
        '55: Colar das Marés, Item, Chame uma onda ou corredeira maciça para sua localização com um rolamento de CAR',
        '56: Botas de Corrida de Parede, +4 DEFESA, Use uma superfície vertical para movimento, quando movendo LONGE',
        '57: Globo de Lâminas, Item, Você é cercado por facas pairando, os atacantes sofrem dano de ARMA',
        '58: Tinta de Alacar, Item, 3 usos, Desenhe qualquer coisa, ela se torna real em todos os aspectos por 2D4 RODADAS',
        '59: Manto de Muitos Bolsos, +2 DEFESA, PILHAGEM mágica não ocupa espaço em seu inventário',
        '60: Caltrops de Fogo, Item, 3 usos, Espalhe espinhos que inflamam qualquer coisa que os toca, depois se queimam',
        '61: Sentinela Espóreo, Criatura, Guerreiro Micnóide que não pode se mover, mas luta com uma lança, fala',
        '62: Pó Demoníaco, Item, 5 usos, Acenda essa poeira inflamável para conjurar um DEMÔNIO instantaneamente',
        '63: Colar de Balthus, +5 DEFESA, Um anel de pescoço que prende o usuário a obedecer você',
        '64: Vestes de Maestria, +5 DEFESA, Ganhe 3 MAESTRIA em qualquer TIPO de FEITIÇO enquanto estiver vestindo',
        '65: Ankh de Sett, Item, Se você rolar um natural 20 para se levantar da MORTE, volte à vida com HP completo',
        '66: Bigorna de Guerra Anã, Item, Uma bigorna e ferramentas com rodas, Crie qualquer item de metal com FOR',
        '67: Pena de Antoine, Item, Escreva qualquer FEITIÇO que você conheça em um pergaminho para que qualquer um possa lançá-lo uma vez',
        "68: Ponte de Lança, Arma, Jogue para formar uma ponte de 30' de comprimento e 6' de largura, colapse com um comando",
        '69: Livro de Goma, Livro, Configure como uma armadilha. Se lido, o leitor fica preso naquele local por 1D8 RODADAS',
        '70: Manto de Brasas, +4 DEFESA, Lance qualquer FEITIÇO que use fogo sem custo',
        '71: Fusível Arcano, Item, 5 usos, FEITIÇOS lançados nesta corda fina entram em efeito em 1D4 RODADAS',
        '72: Frasco de Água Pesada, Item, Use seu FEITIÇO DE TOQUE DE CURA para criar POÇÕES de cura engarrafadas',
        '73: Anel de Resolução, +3 DEFESA, Ignore qualquer ataque contra você de 5 ou menos',
        '74: Wigglers, Comida, 10 usos, Pupa de sapo-pino, Coma com rolagem de CON para HP completo, se falhar, ganhe 1 HP',
        '75: Faber Infinitum, Livro, Leia com uma rolagem de INT e obtenha plantas do seu local atual',
        '76: Gorro Minish, +3 DEFESA, Um chapéu de bruxo de aba larga, com bolsos, você não tem limite de inventário',
        '77: Anel de Gehenna, Item, +1 em todos os ATRIBUTOS, Conjure uma porta para A Biblioteca Arcana',
        '78: Livro das Comunalidades, Livro, Quando concedido MAESTRIA pelo Mestre, aplique-o a qualquer TIPO',
        '79: Livro Mortífero, Livro, Os métodos da morte. Qualquer vítima que você reduza a 5 HP cai para 0',
        '80: Almanaque de Skolari, Livro, PORTAIS permanecem abertos por mais 1 RODADA para você',
        '81: Guia do Espírito de Tobin, Livro, Saiba os detalhes de qualquer monstro que encontrar com uma jogada de INT',
        '82: Tomo das Linhas do Tempo, Livro, Mantenha o conhecimento de tempos alternativos, não importa o que aconteça',
        '83: Crânio de Vincent Aligeeri, Item, Um crânio ventríloquo funciona como sua voz a qualquer distância',
        '84: Render, Espada Grande, ULTIMATE, O dano causado com essa arma também afeta a DEFESA',
        '85: Il-Zah´red, Cimitarra, Mágica, Uma arma, tão perfeita, tão afiada, que você ataca sem jogar dados',
        '86: Manuscrito de Myre, Livro, Adquira todas as habilidades e propriedades de um Horror do Cérebro',
        '87: Pergaminho da Descoberta, Item, 1 Uso, Procurando por algo? Destrua este pergaminho e encontre-o instantaneamente',
        '88: Windchaser, Veículo, Barco em miniatura que cresce instantaneamente para o tamanho normal, 20 SUPRIMENTOS, comporta 8 tripulantes',
        '89: Garfo de Dowsing de Olfan, Item, Jogue INT para encontrar 1D6 INGREDIENTES RAROS em qualquer lugar',
        '90: Óleo da Redenção, Comida, 3 usos, Criaturas malignas que o consomem se tornam boas',
        '91: Tubo de Pergaminhos, Item, Um tubo com 5 PERGAMINHOS DE FEITIÇOS, o mestre escolherá quais FEITIÇOS',
        '92: Cidade de Littleton, Item, Uma pequena cidade com 500 habitantes, contida em uma garrafa de vidro',
        '93: Estojo do Colecionador de Ossos, Bagagem, Queime ossos em vez de seus pontos de habilidade como custo, inclui 16 ossos',
        '94: Ironbrand, Escudo, +8 DEFESA, Aliados PRÓXIMOS a você também ganham esse bônus de DEFESA',
        '95: Hoodria Petrificatum, +4 DEFESA, Levante o capuz deste manto e se torne uma pedra sólida',
        '96: Prisma de Dispersão de Cristal, Item, Refrata qualquer FEITIÇO, ele é triplicado de qualquer maneira que você inventar',
        '97: Matéria Prototipo, Substância, 1 uso, Forme essa massa de gosma em qualquer ITEM em qualquer TABELA DE SAQUE',
        '98: Spellstar, Item, Quando você QUEIMAR um FEITIÇO, não pague nenhum CUSTO e regenere o FEITIÇO',
        '99: Magnífico Entitizer de Zeke, Item, Conceda a qualquer criatura o poder de atravessar objetos sólidos por 1D8 dias',
        '100: Anel do Poder, +5 DEFESA, +2 ESTATÍSTICAS, Não deixe pegadas, Lance todos os FEITIÇOS de nível I sem custo',
      ]
      break
    default:
      var valoresTabela = [
        '1: Pães Mofados: Comida, cura 5 pontos de vida, mas tem um sabor simplesmente horrível',
        '2: Levitação: Feitiço de INT, encanta um alvo para flutuar até 1,8 metros de altura por 1D4 rodadas',
        '3: Identificar: Feitiço de INT, dá a um alvo +3 em uma rolagem de INT/Pesquisa, não é necessária uma tentativa para lançar o feitiço',
        '4: 10 Flechas Mágicas: Item, Dano mágico com um tiro de arco, pode ser recuperada, destruída em falha crítica',
        '5: Lanche Veloz: Comida, ganha um bônus de MOVIMENTO após seu próximo MOVIMENTO',
        '6: Picadas de Aranha: Comida, cura 2D6 pontos de vida, mas você está basicamente comendo um inseto',
        '7: Banquete de Dedos: Comida, cura todos os aliados em 1D8 se estiverem a CURTA distância',
        '8: Armadura de Fé: Feitiço de WIS, dá a um alvo +3 DEFESA por 1 turno',
        '9: Espada de Prata: Arma, +1 Esforço, propriedades de prata',
        '10: Rede com Espinhos: Arma, teste de FOR para escapar, emaranhado, mover apenas para PERTO e todas as rolagens difíceis',
        '11: Kit de Disfarce: Item, sempre que enganar um estranho, faça um esforço FINAL e rolagens FÁCEIS',
        '12: Colete de Mithril: Armadura, subtrai 2 de todo o dano de arma contra você',
        '13: Amuleto de Égide: Item, role 1D8 quando morrer',
        '14: Coração de Iradrum: Comida, por 24 horas após comer, se você chegar a 0 pontos de vida, recupera instantaneamente 1 ponto de vida',
        '15: Bacon Irado: Comida, cura 3D12 pontos de vida',
        '16: Botas de Nado: Armadura, +1 DEFESA, esforço duplo e alcance ao nadar',
        '17: Gar Vermelho: Comida, cura para pontos de vida completos, absorve o próximo ataque ileso',
        '18: Manto das Sombras: Armadura, +1 DEFESA, rolagens FÁCEIS ao se esconder',
        '19: Escudo do Leão: Armadura, +2 DEFESA, aliados que estão PERTO também recebem +2 DEFESA',
        '20: Elmo do Demônio: Armadura, +1 DEFESA, +3 CHA ao intimidar',
        '21: Toque de Cura: Feitiço de WIS, toque para curar um aliado com Esforço Mágico',
        '22: Nova de Cura: Feitiço de WIS, cura todos os aliados PERTO com Esforço Mágico duplo',
        '23: Videira de Agarrão: Feitiço de WIS, puxa um monstro ou aliado PERTO com você, resistência oposta de FOR para resistir',
        '24: Raio de Luz: Magia INT, queima 1-12 HP e adiciona a um ataque mágico, dobra contra armaduras de metal.',
        '25: Explosão de Gelo: Magia INT, causa dano mágico e imobiliza o alvo por 1 turno.',
        '26: Bomba Arcana: Magia INT, um orbe brilhante que explode em 2D12 após 1D4 ROUNDS, alcance PERTO.',
        '27: Machado de Batalha Rasgado: Arma, -2 para tentativas, mas role ESFORÇO FINAL a cada vez.',
        '28: Bola de Fogo: Magia INT, atinge quaisquer alvos dentro do alcance PERTO de uma determinada localização.',
        '29: Botas de Garra: Armadura, permite andar em qualquer superfície em qualquer direção sem precisar de um teste.',
        '30: Pedra do Coração: Item, aumenta em 1 o número máximo de Corações.',
        '31: Encantamento: Magia SAB, encanta um item para realizar um esforço mágico e adicionar +1 a cada Coração de Esforço gasto.',
        '32: Grimório Encantado: Item, um resultado natural 19+ é considerado um acerto crítico ao conjurar magias.',
        '33: Amuleto do Guerreiro: Item, permite usar esforço mágico com qualquer arma.',
        '34: Escudo Divino: Magia SAB, encanta um alvo para absorver o próximo esforço feito contra ele.',
        '35: Cajado dos Elementos: Item, triplica o esforço mágico elemental feito com magias INT.',
        '36: Capa de Aras: Armadura, desvia 1 ataque de arma contra você por turno.',
        '37: Luvas de Prata: Armadura, +3 FOR ao agarrar ou agarrar, propriedades de prata.',
        '38: Gancho de Ferro: Arma, use um turno para puxar um alvo até a sua localização, alcance LONGE.',
        '39: Repelir Mortos-vivos: Magia SAB, por 1 turno, repele 1D8 mortos-vivos, que não podem se aproximar dentro do alcance PERTO.',
        '40: Fragmento de Terror: Item, causa pânico, alvos vivos devem resistir com SAB ou fugir por um turno.',
        '41: Ressurreição: Magia SAB, rolagem DIFÍCIL, em 4 ROUNDS um alvo falecido tocado é revivido com 1 HP.',
        '42: Orbe do Dragão: Item, causa 4D12 de dano mágico de fogo, alcance LONGE, o item é destruído.',
        '43: Elmo do Dragão: Armadura, +2 DEFESA, o usuário é imune a danos infligidos por fogo.',
        '44: Anel de Fantasmas: Item, role INT para criar um clone PERTO que realiza o mesmo ataque ou ação.',
        '45: Coroa da Loucura: Item, faz um alvo realizar uma ação aleatória (rolagem do GM).',
        '46: Asas de Roc Defumadas: Comida, permite voar por 4 ROUNDS.',
        '47: Gar Preto: Comida, +10 DEFESA por 4 ROUNDS.',
        '48: Beijo da Rainha: Comida, Sua próxima ação é um sucesso crítico automático.',
        '49: Afiamento: Magia de INT, Adicione +2 de esforço a uma arma, uma vez por arma.',
        '50: Escudo Espinhoso: Armadura, os ataques falhos do inimigo são respondidos com Dano de Arma (sem bônus).',
        '51: Arco das Águias: Arma, use um turno extra mirando para causar o dobro de dano',
        '52: Enxame: Magia de SAB, lançada em uma área vista, causa dano mágico nos alvos PRÓXIMOS por 1D4 ROUNDS.',
        '53: Curandeiro: Magia de INT, conserta instantaneamente um item ou arma danificados.',
        '54: Escudo de Crânio: Armadura, +2 DEFESA, também pode ser usada como arma mágica.',
        '55: Lança de Prata: Arma, mágica, +3 de TENTATIVA de DEX quando arremessada, propriedades de prata.',
        '56: Bigorna Anã: Item, uma vez a cada 1D12 dias, cria uma arma com +3 de TENTATIVA ou bônus de ESFORÇO.',
        '57: Livro de Habilidades: Item, com 3 sucessos, ganhe permanentemente +1 para um tipo específico de TENTATIVA.',
        '58: Anel de Fogo: Item, dobra todo o dano de fogo infligido.',
        '59: Espada Flamejante: Arma, mágica, adiciona 1D4 de dano de queimadura por 1D4 ROUNDS nos alvos acertados.',
        '60: Anel de Gênio: Item, use ESFORÇO FINAL com qualquer rolagem bem-sucedida de INT.',
        '61: Cálice de Udin: Item, dobra os efeitos de qualquer comida consumida.',
        '62: Anel de Aras: Item, ao se recuperar, preencha um CORAÇÃO além de sua RECUPERAÇÃO normal.',
        '63: Pedra do Coração: Item, adiciona 1 coração ao seu máximo.',
        '64: Translocar: Magia de INT, troca de lugar com um aliado que você pode ver.',
        '65: Máscara de Mofune: Armadura, +1 DEFESA, role ESFORÇO FINAL ao intimidar.',
        '66: Anel de Poder: Item, dobra todo o ESFORÇO MÁGICO.',
        '67: Selo do Rei: Item, ter a última palavra em decisões de grupo e ser amado por isso.',
        '68: Martelo Anão: Arma, arma mágica, role ESFORÇO FINAL dobrado em 20 natural.',
        '69: Ferramentas de Ladrão: Item, +3 de TENTATIVA E ESFORÇO DOBRADO ao abrir baús.',
        '70: Anel de Gigantes: Item, +1 de STR, +1 DEFESA.',
        '71: Botas Magistrais: Item, +1 DEX',
        '72: Caneca do Rei: Item, +1 CON',
        '73: Amuleto dos Segredos: Item, +1 INT',
        '74: Contas de Meditação: Item, +1 WIS',
        '75: Casacos Magistrais: Item, +1 CHA',
        '76: Kit de Armadura: Item, +2 DEFESA',
        '77: Pedra de Fogo: Item, +1 Esforço MÁGICO',
        '78: Kit de Armas: Item, +2 Esforço de Armas',
        '79: Luneta de Diamante: Item, +6 WIS em tentativas de Exploração',
        '80: Anel Berserk: Item, +3 em Esforço ÚLTIMO',
        '81: Baluarte Sagrado: Feitiço WIS, Toque um aliado, eles são imunes a Esforço não-MÁGICO por 4 ROUNDS',
        '82: Tempestade: Feitiço WIS, Tudo com alcance LONGO é atingido por granizo para MÁGICA',
        '83: Carne Seca: Comida, Regenera 1D12 HP para os próximos 4 ROUNDS',
        '84: Hauberk de Adamantina: Armadura, +4 DEFESA',
        '85: Bebedor de Vida: Arma, Arma Mágica, Cura metade do dano causado a alvos vivos',
        '86: Pulseiras de Poder: Armadura, DEFESA +1, Role 1D8 para qualquer Esforço Básico',
        '87: Cinto de Ferro Gut: Armadura, +1 DEFESA, Se falhar em um teste de CON, tente mais uma vez',
        '88: Cerveja da Morte: Comida, Retorna da morte com 10 HP. Desperdiçada se não for usada dentro de 1 dia após beber',
        '89: Cerveja da Vida: Comida, Beba em batalha. Qualquer aliado que o tocar cura 1D12 HP uma vez',
        '90: Óculos do Gadgets: Armadura, +1 DEFESA, Criar ou consertar máquinas é sempre FÁCIL',
        '91: Pena de Queda: Item, Você não pode se machucar por danos de queda de qualquer altura',
        '92: Dobra-Tempo: Item, Se o GM rolar um cronômetro, role novamente. A segunda rolagem será final',
        '93: Maça do Trovão: Arma, Mágica, Qualquer alvo atingido fica atordoado em seu próximo TURNO',
        '94: Corcel Relâmpago: Item, Invoca um corcel voador. O que levaria um dia, leva 1 ROUND',
        '95: Anel da Sorte Estranha: Item, Se você rolar um 1 duas vezes, seu erro causa algo benéfico',
        '96: Anel Artesão de Magias: Item, Se você rolar um crítico ao lançar uma magia, tente outra magia imediatamente',
        '97: Botas da Pressa: Armadura, DEFESA +1, Após uma ação, você também pode se mover novamente',
        '98: Anel de Matadores: Item, Se você fizer um ataque bem-sucedido com uma arma, ataque novamente para o ULTIMATE',
        '99: Coroa Astral: Armadura, +2 DEFESA, Ao lançar uma magia crítica, lance através de um aliado',
        '100: Banquete dos Reis: Comida, Todos os aliados restauram HP completo e recebem um Baú',
      ]
  }

  document.getElementById('resultado').innerHTML = valoresTabela[resultado - 1]
}
